### ISSUE TITLE
has any way to exclude ionic components and theme?

### ISSUE THREAD

**Issue by izee** [ionic-team/ionic-app-scripts#1005]
i want to use ionic2 with a clean style environment for use customize or 3rd part components, the ionic2 themes and styles has many destructive.

**Comment by rapropos** [comment]
Ionic without Ionic components or styles is Cordova, so you could just use that.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
