### ISSUE TITLE
how to add my own polyfill

### ISSUE THREAD

**Issue by yozman** [ionic-team/ionic-app-scripts#1007]
how to add my own polyfill?
angular datepipe isn't work,
and I want to add Intl polyfill
to `polyfill.js` use `build --prod`,

could u tell please me
what should I do?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Comment by realappie** [comment]
But really, how do we do it.
