### ISSUE TITLE
How to package a third-party library separately into a file？

### ISSUE THREAD

**Issue by lifesreason** [ionic-team/ionic-app-scripts#1014]
Now I want to pack the ionic angular jQuery... into a separate file inside, write their own code into a document inside, how should I do? Is there any solution or instance?

**Comment by rapropos** [comment]
Please send support requests to [the forums](https://forum.ionicframework.com/).

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
