### ISSUE TITLE
[ionic 3.3.0] Error: Failed to install apk to device

### ISSUE THREAD

**Issue by thorizer** [ionic-team/ionic-app-scripts#1021]
I'm encountering an error when running :  ionic cordova run android
>ionic cordova run android
build dev started 
...
**BUILD SUCCESSFUL**
Built the following apk(s): 
	C:/.../platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=D:\Users\SBS\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121
No target specified, deploying to device '96cac6f8'.
Skipping build...
Built the following apk(s): 
	C:/.../platforms/android/build/outputs/apk/android-debug.apk
Using apk: C:/.../platforms/android/build/outputs/apk/android-debug.apk
Package name: io.ionic.starter
**Error: Failed to install apk to device: [  1%] /data/local/tmp/android-debug.apk**
[  2%] /data/local/tmp/android-debug.apk
...
[100%] /data/local/tmp/android-debug.apk
C:/Amine/Work/Ionic/WS/dota5/platforms/android/build/outputs/apk/android-debug.apk: 1 file pushed. 2.6 MB/s (5156463 bytes in 1.865s)
	pkg: /data/local/tmp/android-debug.apk
**Failure [INSTALL_FAILED_CONTAINER_ERROR]**
**[ERROR] Cordova encountered an error.**
        You may get more insight by running the Cordova command above directly.      
**[ERROR] An error occurred while running cordova run android (exit code 1).**

## **Ionic info:**
**global packages:**

ionic/cli-utils      : 1.3.0
Cordova CLI      : 6.5.0
Ionic CLI            : 3.3.0

**local packages:**

ionic/app-scripts                      : 1.3.7
ionic/cli-plugin-cordova          : 1.3.0
ionic/cli-plugin-ionic-angular  : 1.3.0
cordova platforms                       : android 6.1.2
Ionic Framework                          : ionic-angular 3.3.0

**System:**

Node       : v6.10.1
OS           : windows 10

I also upgraded Cordova CLI to 7.0.1 but I still have the same issue

**Comment by Supriya412** [comment]
Did you get its solution? I am sticking with the same issue, How you resolved Please share.

**Comment by ThangaBharaniTharan** [comment]
Hi, all 
Uninstall  app in your device & check again  ...

**Comment by wcjord** [comment]
I've got the same issue!

**Comment by Supriya412** [comment]
@wcjord.. This usually occurs when we change our development environment and try to install the new application among the old one in our device, for winning this error, you have to uninstall all the existing ionic application in your device and install the new app again, this will surely work.
Thanks

**Comment by clmorales** [comment]
Thanks @Supriya412 works for me too.

**Comment by AlexKhl** [comment]
> Hi, all
> Uninstall app in your device & check again ...

Thank you friend!
