### ISSUE TITLE
Properties are not mangled when uglifying and there is no option for it

### ISSUE THREAD

**Issue by krz37** [ionic-team/ionic-app-scripts#1029]
#### Short description of the problem:
The uglified JS can be easily read and the developer does not have the possibility to mangle properties.

#### What behavior are you expecting?
I expected that there would be a command-line option to mangle properties using the API UglifyJS
provides for it.

**Steps to reproduce:**
1. Use `ionic cordova build android --release --prod`
2. unzip the output
3. check assets/www/build/main.js

**Which @ionic/app-scripts version are you using?**
1.3.7

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I have tried adding ` mangleProperties: {}` to `node_modules/@ionic/app-scripts/config/uglifyjs.config.js` manually but that did not help, despite it it documented this way on [https://github.com/mishoo/UglifyJS2/tree/v2.8.22](https://github.com/mishoo/UglifyJS2/tree/v2.8.22)

**Comment by jgw96** [comment]
Hello! At this time because of how `mangleProperties` works and how strict it is we have decided not to turn it on as it will not work with the majority of third party libs at the moment.
