### ISSUE TITLE
ionic build android --prod  failed

### ISSUE THREAD

**Issue by coolara** [ionic-team/ionic-app-scripts#1033]
```
> ionic-app-base@ ionic:build D:\03-bak\baiduoke
> ionic-app-scripts build "--prod" "--verbose"

```
```
[11:15:15]  ionic-app-scripts 1.1.4
[11:15:15]  build prod started ...
[11:15:15]  clean started ...
[11:15:15]  clean finished in 46 ms
[11:15:15]  copy started ...
[11:15:15]  ngc started ...
[11:17:19]  ngc finished in 123.21 s
[11:17:19]  preprocess started ...
[11:17:19]  optimization started ...
[11:17:24]  copy finished in 129.07 s
[11:19:10]  optimization finished in 111.31 s
[11:19:10]  preprocess finished in 111.32 s
[11:19:10]  webpack started ...
[11:25:37]  webpack finished in 386.92 s
[11:25:37]  sass started ...
[11:25:37]  transpile bundle started ...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! ionic-app-base@ ionic:build: `ionic-app-scripts build "--prod" "--verbose"`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the ionic-app-base@ ionic:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging out
put above.

ionic info:
PS D:\03-bak\baiduoke> ionic info

Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed

```
ionic build ios --prod  go right
but in windows i got  above errors
my internal memory is 8g

**Comment by piotrowski** [comment]
How did it fail? The actual error message is missing.

Rerun the same command with `--verbose` at the end for more output.

**Comment by coolara** [comment]
@piotrowski  i have update my error

**Comment by piotrowski** [comment]
As this works for many others but not you and is related to memory, this is not really a bug or issue with app-scripts.

Also your Ionic CLI and App Scripts versions are quite old, update them to the newest ones and try again. Probably this was some kind of bug that has already been fixed.

If this doesn't help, please open a topic in the Ionic Forum at https://forum.ionicframework.com/. Thanks.

**Comment by coolara** [comment]
thank you ,PS D:\03-bak\baiduoke> ionic cordova build --help
? Looks like this is an Ionic Angular project, would you like to install @ionic/cli-plu
gin-ionic-angular and continue? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✖ Running command - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-p
lugin-ionic-angular@latest (exit code 1):

        npm ERR! Maximum call stack size exceeded

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\kid\AppData\Roaming\npm-cache\_logs\2017-06-11T11_21_34_89
5Z-debug.log

i have encounted another error , can you help me

**Comment by piotrowski** [comment]
Please post at the forum and include your `ionic info` output.

**Comment by coolara** [comment]
D:\03-bak\baiduoke> ionic info
? Looks like this is an Ionic Angular project, would you like to install @ionic/cli-plu
gin-ionic-angular and continue? (Y/n)

**Comment by piotrowski** [comment]
Last time I will answer to you: Post this at https://forum.ionicframework.com/

(Run `ionic info` outside of the project)

**Comment by coolara** [comment]
thank you for your time
