### ISSUE TITLE
Can't install 1.3.7 on Windows

### ISSUE THREAD

**Issue by Peluko** [ionic-team/ionic-app-scripts#1039]
#### Short description of the problem:

Can't do `ionic serve` because I can't install ionic-app-scripts on Windows 10 64 bits

#### What behavior are you expecting?

`ionic serve` must install ionic-app-scripts and run smoothly on Windows 10 64 bits

**Steps to reproduce:**

1. Create a new ionic app with the latest cli on Windows 10 64 bits
2. Run `ionic serve` on the project
3. It requests ionic-app-scripts, but the installation fails while installing `node-sass`

The problem is that ionic-app-scripts 1.3.7 refers to node-sass 4.5.0. The node-sass installation request for precompiled binaries, which can't be found for my Windows 10 64 bits platform (request for `https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node` receiving a 404). This binaries can't be downloaded and then fails trying to compile sass.

`node-sass` 4.5.3 installs perfectly on Windows, so the solution might be to upgrade the reference.

**Comment by themastersoda** [comment]
It has already been updated, but the new version has not been published to npm for some reason.

**Comment by Peluko** [comment]
Yeah, I've just seen that. But I want to do some demos, so I need it on npm, pleeease!!

**Comment by janpio** [comment]
It can not be released to npm as it hasn't be tagged and released yet.

Are you using node8/npm5 by chance? If so, this change is the reason why this doesn't work yet. use another version for now.

**Comment by Peluko** [comment]
Well, I've downgraded to node 7.10.0/npm 4.2.0 and now it works again. Thanks!

**Comment by Nexeuz** [comment]
with `npm install -g npm@4.2.0` you can downgrade npm

**Comment by rokanost** [comment]
`npm install @angular/tsc-wrapped` (inside the project) did it for me.
