### ISSUE TITLE
bug: Java Heap out of mem: Fatal Error on `ionic serve`

### ISSUE THREAD

**Issue by itsru** [ionic-team/ionic-app-scripts#1050]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Javascript Heap out of memory

**Steps to reproduce:**
1. ionic serve -c

```
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>When running 'ionic serve -c' I get 

[03:19:09]  transpile started ... 

<--- Last few GCs --->

  291753 ms: Mark-sweep 1317.9 (1432.4) -> 1312.3 (1432.4) MB, 385.9 / 0.0 ms [allocation failure] [GC in old space requested].
  292172 ms: Mark-sweep 1312.3 (1432.4) -> 1312.3 (1432.4) MB, 418.9 / 0.0 ms [allocation failure] [GC in old space requested].
  292621 ms: Mark-sweep 1312.3 (1432.4) -> 1312.3 (1401.4) MB, 449.3 / 0.0 ms [last resort gc].
  293046 ms: Mark-sweep 1312.3 (1401.4) -> 1312.3 (1401.4) MB, 425.2 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3158a58cfb39 <JS Object>
    1: [Symbol.replace] [native regexp.js:~540] [pc=0x14a1867d8c7c] (this=0x3ba250987f09 <JS RegExp>,D=0x2a08a33ed069 <Very long string[1854239]>,aw=0x3158a58ec999 <String[1]\: \n>)
    2: 0x3158a588aaf1 <Symbol: 20329980 <String[14]: Symbol.replace>>(aka [Symbol.replace]) [native regexp.js:~659] [pc=0x14a186675f2b] (this=0x3ba250987f09 <JS RegExp>,D=0x2a08a33ed069 <Very long string[1854239]>,a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Runtime_StringReplaceGlobalRegExpWithString(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x14a1844092a7
 8: 0x14a1867d8c7c
 9: 0x14a186675f2b
Abort trap: 6

----------------------------------
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10</span>

<span is-issue-template></span>

```

**Which @ionic/app-scripts version are you using?**
1.3.7

**Comment by webberig** [comment]
I'm having the same issues. My ionic info:

```

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Gulp CLI         : not installed globally
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-gulp          : 1.0.1
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.11.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1
```

**Comment by webberig** [comment]
I'm still trying to figure out why this is happening. It works fine if I run ionic inside a docker container, so it has nothing to do with my app but rather my system. I tried uninstalling node completely and remove all references (such as /usr/local/lib/node_modules), but so for no good...

**Comment by webberig** [comment]
I managed to resolve it by removing node entirely from my system:
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

I didn't really find the precise cause, but it seems to be solved for me...

**Comment by itsru** [comment]
@webberig What source did you use to install node after you removed it entirely?

**Comment by webberig** [comment]
I read a comment somewhere saying that Ionic is not yet compatible with
Node 8 and Npm 5.

I used following command with Homebrew:

    brew install node@6

This still installs Npm 5, but you can easily downgrade it:

    npm install -g npm@4




2017-06-24 4:09 GMT+02:00 Ru Selvadurai <notifications@github.com>:

**Comment by itsru** [comment]
I've given this a few different goes. 

it seems to still be an issue in osx with my project. I have gotten it to work with the latest ionic and app-scripts releases and the same project.

On osx I have successfully run it with a new `tabs` project but it still fails with my project.

**Comment by ztecharoberts** [comment]
This is how others and I have gotten past this issue.

https://github.com/angular/angular/issues/12184#issuecomment-278889228

**Comment by itsru** [comment]
@ztecharoberts I have tried that but it still fails with 16GB of ram assigned. 

I have successfully done a serve and build of this project in windows with no modifications to the `old space` but on osx it has the heap issue.

What versions of npm and node are you running in osx?

**Comment by ztecharoberts** [comment]
@itsru 

Cordova CLI: 7.0.1 
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
