### ISSUE TITLE
polyfills.js & sw-toolbox.js do not have sitemaps generated

### ISSUE THREAD

**Issue by fephil** [ionic-team/ionic-app-scripts#1051]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

When running any task which produces Javascript sitemaps, polyfills.js & sw-toolbox.js never have sitemaps generated alongside them. This is more of a problem for polyfills.js as errors reported in Sentry JS normally contain a reference to polyfills in the stack trace.

Thanks.

#### What behavior are you expecting?

Sitemaps to be generated for polyfills.js & sw-toolbox.js

**Steps to reproduce:**
1. Run any ionic task eg `npm run build --prod --generateSourceMap true`

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
1.3.7

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by SeanZhouSiyuan** [comment]
Hi @fephil, is the problem solved? I'm having the same issue. Thanks.
