### ISSUE TITLE
`ionic serve` taking extremely long to start

### ISSUE THREAD

**Issue by jacquesdev** [ionic-team/ionic-app-scripts#1067]
#### Short description of the problem:
Not 100% sure if this is the correct repo to discuss the issue, and if not - apologies.

I have an ionic 1 project, using ionic cli 3.4.0, and as far as I can see I don't use ionic-app-scripts directly, but I guess that it's an integrated part of the cli? When I run `ionic serve`, it seems like nothing is happening for about 4-5 minutes. When I run it with verbose, I can see what is happening.

```
mac-mini:mobile jacques$ ionic serve -b --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
[DEBUG] Detected ./gulpfile.js in project directory
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-gulp
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic1
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Getting plugin info for ionic
[DEBUG] Getting plugin info for @ionic/cli-plugin-cordova
[DEBUG] Getting plugin info for @ionic/cli-plugin-gulp
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic1
[DEBUG] Getting plugin info for @ionic/cli-plugin-proxy
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-cordova@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-gulp@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic1@latest.
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-proxy@latest.
[DEBUG] Latest version of ionic@latest is 3.4.0.
[DEBUG] Latest version of @ionic/cli-plugin-proxy@latest is 1.3.1.
[DEBUG] Latest version of @ionic/cli-plugin-ionic1@latest is 2.0.0.
[DEBUG] Latest version of @ionic/cli-plugin-gulp@latest is 1.0.1.
[DEBUG] Latest version of @ionic/cli-plugin-cordova@latest is 1.4.0. 
```

#### What behavior are you expecting?
I expect that ionic serve should pretty much just run immediately and not wait to check for the latest versions, because in some cases this takes incredibly long. Happy to see an info message if one of the scripts is out of date, but it should definitely not hang the entire process for me to run up a server.

**Which @ionic/app-scripts version are you using?**
Running ionic info displays:

global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 7.0.1 
    Gulp CLI                : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI               : 3.4.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.0
    @ionic/cli-plugin-gulp    : 1.0.1
    @ionic/cli-plugin-ionic1  : 2.0.0
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : unknown

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : not installed
    npm        : 3.10.10 

Any help is appreciated.

**Comment by janpio** [comment]
> Not 100% sure if this is the correct repo to discuss the issue, and if not - apologies.

The output you see is generated by the CLI directly I think, so you might want to open an issue over there: https://github.com/ionic-team/ionic-cli/issues

Maybe there already is a flag or config to skip the update checks, I am not sure - best ask in the issue over at the CLI as well then.

Do you get the output you posted over time or all at once after waiting for x minutes? Is your connection really slow, so is there a reason why it takes so long, or is this also mysterious?

**Comment by jacquesdev** [comment]
Thanks @janpio. 

The output gets posted over time, and no my connection is not slow. It happens once every week or so (but I have only been using the updated CLI for three weeks now). I realise that it may happen in a time when my connection is slow for some reason, but I would prefer to control those updates. Will close this and create a new issue in the correct repo.

**Comment by janpio** [comment]
There is probably a check in the CLI that it doesn't check for updated versions every time it runs - and these could be the ones that are slow for you. Ask for it in the other issue as well.
