### ISSUE TITLE
/ionic-lab: Ad text is hidden

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-app-scripts#1078]
New /ionic-lab added a new ad spot in the left menu. The text is hidden, the icon next to it is not:

![hidden-ad](https://user-images.githubusercontent.com/183673/27829362-887040a2-60c1-11e7-9d10-699c5dbf4c48.PNG)

(Chrome 59 on Windows 10)

**Comment by jgw96** [comment]
Hello @janpio , with the latest version of the cli and app-scripts and chrome 59 on my surface book running the latest build of Windows 10 i cannot reproduce this issue anymore.

**Comment by janpio** [comment]
lol damn, now that I think about it:
I should have probably disabled my adblocker...

![image](https://user-images.githubusercontent.com/183673/28435646-2f196698-6d94-11e7-8f6f-4954c8c772d2.png)
Easylist has a rule against this ID you are using.
