### ISSUE TITLE
Multiple Webpack Configs break Compilation

### ISSUE THREAD

**Issue by sqwk** [ionic-team/ionic-app-scripts#1079]
I extended the ionic app-scripts webpack config by adding another section that compiles a typescript electron app:

    module.exports = [
        { // Uncchanged ionic app-scripts webpack config },
        { // Another Webpack config with seperate entry points }
    ]

In webpack this normally works. When running `ionic serve` or similar, the app is compiled without errors but is missing `main.js` and `main.css`. (404) When checking the www folder the compiled places are missing.

Is it possible to piggyback onto the ionic webpack config to do something else? Or do these have to be handled separately?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! At this time we cannot provide official support for custom webpack configs. You might could try our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/) for help with that. Also you can override our webpack config and can learn how to do so [here](https://github.com/ionic-team/ionic-app-scripts#overriding-config-files).
