### ISSUE TITLE
@ionic/cli-plugin-ionic-angular@1.3.1 requires a peer of @ionic/app-scripts@^1.3.7

### ISSUE THREAD

**Issue by aggarwalankush** [ionic-team/ionic-app-scripts#1083]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
While updating app scripts from 1.3.7 to 2.0.0, I'm getting error- 
@ionic/cli-plugin-ionic-angular@1.3.1 requires a peer of @ionic/app-scripts@^1.3.7

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
annaggarwal@LM-SJN-21001708:RimsMobile$ npm install @ionic/app-scripts@latest --save-dev

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/annaggarwal/Documents/IdeaProjects/RimsMobile/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN @ionic/cli-plugin-ionic-angular@1.3.1 requires a peer of @ionic/app-scripts@^1.3.7 but none was installed.
npm WARN tslint-eslint-rules@4.1.1 requires a peer of tslint@^5.0.0 but none was installed.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none was installed.
npm WARN RiMS@ No repository field.
npm WARN RiMS@ No license field.

+ @ionic/app-scripts@2.0.0
added 30 packages, removed 14 packages, updated 1 package and moved 10 packages in 7.259s
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by mhartington** [comment]
Note: these are only warnings, and not actual errors. Your project will still build and run as expected. We just need to update some versions in the cli-plugins.

**Comment by aggarwalankush** [comment]
@mhartington didn't notice it was just a warning 👍
