### ISSUE TITLE
The resource from “http://localhost:8100/build/vendor.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

### ISSUE THREAD

**Issue by MvRemmerden** [ionic-team/ionic-app-scripts#1084]
#### Short description of the problem:
After upgrading to 2.0.0, the following warning shows up in the console.

**Steps to reproduce:**
1. Upgrade app-scripts to 2.0.0
2. run ionic serve
3. check out the console

**Which @ionic/app-scripts version are you using?**
2.0.0

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
