### ISSUE TITLE
App scripts 2.0 breaks whole dev process

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic-app-scripts#1088]
#### Short description of the problem:
```
Error: cmd: Command failed with exit code 4294963238 Error output:
npm WARN @ionic/cli-plugin-ionic-angular@1.3.1-alpha.e838a5d7 requires a peer of @ionic/app-scripts@^1.3.7 but none was installed.
```

#### What behavior are you expecting?
Everything should work?

**Steps to reproduce:**
1. ionic start
2. select blank project
3. check `package.json` under devdependencies, version 2 should be stated.
4. ionic cordova run android --device OR
5. ionic cordova plugin add ANY_PLUGIN

**Which @ionic/app-scripts version are you using?**
2.0, latest release

This is due to incompatibility between `ionic-cli` and latest `ionic-app-scripts`. Someone else has already found the issue, posted on cli:

https://github.com/ionic-team/ionic-cli/issues/2503

**Comment by danbucholtz** [comment]
We'll fix it. Sorry, this was an oversight on our part.

Thanks,
Dan

**Comment by danbucholtz** [comment]
This is now fixed. Will be published soon.

Thanks,
Dan

**Comment by alaaelsm** [comment]
thank you
