### ISSUE TITLE
Deep links process as a separate module/standalone CLI?

### ISSUE THREAD

**Issue by sinedied** [ionic-team/ionic-app-scripts#1091]
#### Short description of the problem:

I'm currently trying to integrate ionic with `angular-cli`, as  I find the `ionic` CLI lacking on many points. 

One of the limitations I have discovered is that the `@ionicPages` decorator rely on a specific `ionic` CLI postprocessing script that can be found here, to generate the deep links.

#### What behavior are you expecting?

Would you consider extracting the deep links scripts in a separate package so it can be integrated with other build systems? A standalone CLI would be even better to allow us to perform this task using only npm scripts.

At least, it could be nice to have some documentation on what it does, so if you don't have the time to extract the code I can try to implement it.

Thanks for considering this.

EDIT: As a bonus, I'm just wondering: why using a build step for this instead of implementing the deep link generation directly in the `@ionicPages` annotation?

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. At this time because deeplinks and `@ionicPages` are so tied into our cli we do not plan on splitting it out anytime soon. Also, at this time we do not currently provide official support for using the Angular cli to build Ionic apps.
