### ISSUE TITLE
ionic-app-scripts 2.0.0 content not updated correctly

### ISSUE THREAD

**Issue by CharlesGrimont** [ionic-team/ionic-app-scripts#1092]
#### Short description of the problem:

With ionic-app-scripts 2.0.0 when I'm updating content on my .ts page changes are not applied correctly..

In fact, when I'm adding for example a console.log in my constructor for the first time the change will be applied, but if I change again this console.log replacing for example console.log("hello") by console.log("hello ionic"); my browser will reload but only hello will be displayed.

However if I made a change on another page the older changed will be applied...

**Steps to reproduce:**
1. ionic start myAmazingIonicApp --v2
2. cd ./myAmazingIonicApp 
3. ionic serve
4. type a console.log("hello"); into anywhere
5. replace this console.log by console.log("hello 2");

**Which @ionic/app-scripts version are you using?** 2.0.0

Thanks in advance !

**Comment by BrunoFDeveloper** [comment]
I have the same issue, after edit .ts file the edit not applied.

**Comment by Lyricalz** [comment]
Same, however if I re-run ionic serve, files are updated as they should be

**Comment by danbucholtz** [comment]
This should be fixed in `nightly`. Please try and let me know how it goes. If you have a custom webpack config, make sure you're updating it to only use ModuleConcatenationPlugin for prod builds.

```
npm install @ionic/app-scripts@nightly
```

Thanks,
Dan

**Comment by BrunoFDeveloper** [comment]
Hello, after install the nightly version i get this error:

![screen shot 2017-07-10 at 16 16 37](https://user-images.githubusercontent.com/4235143/28035482-2578f164-658b-11e7-9358-6aa39b2121dd.png)

`ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0-201707101815
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.1.0 
`
Thanks

**Comment by CharlesGrimont** [comment]
I can confirm that this is fixed in the nightly (2.0.0-201707102058)
Thanks a lot !

**Comment by moberwasserlechner** [comment]
Same here. Update works. Thanks for the quick fix.

```
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
[10:09:57]  ionic-app-scripts 2.0.0-201707102058
[10:09:57]  watch started ...
[10:09:57]  build dev started ...
[10:09:57]  clean started ...
[10:09:57]  clean finished in 2 ms
[10:09:57]  copy started ...
[10:09:57]  transpile started ...
[10:10:01]  transpile finished in 3.56 s
[10:10:01]  preprocess started ...
[10:10:01]  deeplinks started ...
[10:10:01]  deeplinks finished in 353 ms
[10:10:01]  preprocess finished in 535 ms
[10:10:01]  webpack started ...
[10:10:01]  copy finished in 4.21 s
[10:10:13]  webpack finished in 12.03 s
[10:10:13]  sass started ...
[10:10:15]  sass finished in 1.71 s
[10:10:15]  postprocess started ...
[10:10:15]  postprocess finished in 5 ms
[10:10:15]  lint started ...
[10:10:15]  build dev finished in 17.89 s
[10:10:15]  watch ready in 18.18 s
[10:10:15]  dev server running: http://localhost:8100/
```

**Comment by netsesame2** [comment]
Great! This issue disturb me so long time.

**Comment by sasokovacic** [comment]
I get this error when I try to update app-scripts:

npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
transfermarkt@ /media/saso/Data/www/projects/transfermarktApp
└─┬ @ionic/app-scripts@2.0.1-201707121621  invalid
  ├─┬ autoprefixer@7.1.1
  │ └── caniuse-lite@1.0.30000701 
  ├─┬ rollup-plugin-node-builtins@2.1.2
  │ └── crypto-browserify@3.11.1 
  ├─┬ tslint@5.5.0
  │ └── tsutils@2.6.1 
  └─┬ webpack@3.2.0 
    └── UNMET PEER DEPENDENCY ajv@5.2.2
