### ISSUE TITLE
ionic-app-scripts 2.0.0 - iOS header styling lost

### ISSUE THREAD

**Issue by SkogDev** [ionic-team/ionic-app-scripts#1094]
#### Short description of the problem:
After upgrading from 1.3.12 to 2.0.0, any ionic 3 app on iOS loses header styling. 
By the looks of it, the header-bar is missing its original padding, which in turn results in a status-bar on top of the header-bar. This is not an issue on Android.

#### What behavior are you expecting?
The header-bar should look the same on both versions of ionic-app-scripts.

**Steps to reproduce:**
1. ionic start test --type=ionic-angular --> I chose tutorial
2. cd test & ionic cordova platform add ios/build/run
3. tutorial has 2.0.0 as default in package.json, so the issue is presented on first launch.
4. downgrade ionic-app-script to 1.3.12 & npm install.
5. run again. Header-bar is normal.

**Which @ionic/app-scripts version are you using?**
2.0.0

**Comment by mhartington** [comment]
Hmm, Im not able to replicate this at all.
Followed your steps and it worked fine for me.

Could you please push something to github to look at?

**Comment by SkogDev** [comment]
@mhartington Sure, just pushed the code to this repo: [https://github.com/SkogDev/ionic-tutorial](url)

Also, here is an image of the result using 2.0.0: 
![img_3578](https://user-images.githubusercontent.com/2014746/28023716-f04da544-658e-11e7-82a2-dfa7fa0e5e76.PNG)

**Comment by djabif** [comment]
same here!

**Comment by mhartington** [comment]
Hmm, still unable to replicate.

![simulator screen shot jul 10 2017 at 12 25 12 pm](https://user-images.githubusercontent.com/2835826/28028548-e0015678-656a-11e7-9259-6621549ffc6a.png)

**Comment by SkogDev** [comment]
@mhartington That is unfortunate. Here is a print of my ionic-info:

> global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

> local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

> System:

    Node       : v7.2.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
    npm        : 4.0.5

**Comment by mhartington** [comment]
```
$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.2
    OS         : macOS High Sierra
    Xcode      : Xcode 9.0 Build version 9M136h
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.1.0
```

**Comment by SkogDev** [comment]
Perhaps you @djabif would be so kind to inform us how you were able to reproduce the issue?

**Comment by djabif** [comment]
Same as you, I updated app-scripts from 1.3.12 to 2.0.0, added the required lines in index.html, deleted node modules, then run npm install. Then deployed the app to an android and ios device and I see this issue in both platforms.

**Comment by SkogDev** [comment]
That is indeed strange, I have not been able to reproduce this issue on the Android platform.

**Comment by djabif** [comment]
$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.3
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.12 
    npm        : 3.10.10

**Comment by BrunoFDeveloper** [comment]
the same here:
`
ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0-201707101815
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.1.0 

`

**Comment by mhartington** [comment]
Please provide a sample project that has this issue.

**Comment by BrunoFDeveloper** [comment]
Hello, I just created another project to see if the error would still be there and even then it was there, follow the project with error that is the same as my real project.

https://github.com/BrunoFDeveloper/app-example

Thanks.

**Comment by danbucholtz** [comment]
How do I recreate? It looks normal to me.

Thanks,
Dan

**Comment by BrunoFDeveloper** [comment]
Hello, after delete node_modules and re-install my problem was resolved, but I noticed that in the browser the problem continues, the device is already okay.

Thanks.

**Comment by hche608** [comment]
I am having the same issue
![image](https://user-images.githubusercontent.com/6982065/28048160-3e4cd7e2-6643-11e7-886d-8feec5e6c2ca.png)

**Comment by SkogDev** [comment]
@danbucholtz As I wrote in the first post:

1. ionic start test --type=ionic-angular --> I chose tutorial
2. cd test & ionic cordova platform add ios/build/run
3. tutorial has 2.0.0 as default in package.json, so the issue is presented on first launch.
4. downgrade ionic-app-script to 1.3.12 & npm install.
5. run again. Header-bar is normal.

I'm running the application on a real device (iPhone 6s). The issue is present with both "ionic cordova run ios" and "ionic cordova run ios -l".

I have this issue on all my ionic 3 projects, not just the ionic-tutorial.

**Comment by danbucholtz** [comment]
@SkogDev, we'll get it fixed. It seems to occur in these scenarios:

1. When deploying to a device with a non-prod build
2. When using `ionic serve --lab`

Thanks,
Dan

**Comment by SkogDev** [comment]
@danbucholtz Thank you!

**Comment by ngfk** [comment]
I had this problem too, but thought it was because of something I did. Ended up using the code below on platform ready to get it back.

```
statusBar.overlaysWebView(false);
statusBar.backgroundColorByHexString('0c77bd');
```

**Comment by danbucholtz** [comment]
This is fixed in `nightly`.

Thanks,
Dan

**Comment by SkogDev** [comment]
Looks good in nightly! Thanks Dan.

**Comment by emiljohansson** [comment]
@danbucholtz I'm seeing this in 2.0.1 on Android. Compared to how it used to be, the status bar now has a transparent background with no height (similar to iOS), previously it had a black background. On pages where we don't have a ion-header, it acts like iOS where the content scrolls behind the status bar. 
If this is intentional, I can definitely work around it and implement the same solution we have for iOS. If there's a setting to revert the "native" fixed status bar, let me know.

**Comment by emiljohansson** [comment]
Update: We tested this on a few devices with Android version 5, 6, and 7, and we only see this result on 5 and 6. Devices with Android 7 has the native status bar and the app looks as expected.

**Comment by emiljohansson** [comment]
After removing `StatusBar.overlaysWebView(true)` we got the status bar back on android, and iOS remains the same. Not sure why it is working differently with the newer version of the status bar plugin.
