### ISSUE TITLE
[2.0.0] ionic serve not picking up changes

### ISSUE THREAD

**Issue by fiznool** [ionic-team/ionic-app-scripts#1100]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

When making a change in the filesystem, the app builds and reloads, but the new code is not bundled.

#### What behavior are you expecting?

The new code should be bundled.

**Steps to reproduce:**

Unfortunately I can't come up with a reproducible test case. I'll attach a gif which shows the issue occurring on my machine.

**Which @ionic/app-scripts version are you using?**

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.0.3
```

**Comment by fiznool** [comment]
Here's a link to a video which shows the issue.

https://giphy.com/gifs/l4FGodHBMRWQCPqOQ/html5

I'm able to reliably reproduce with the project I have here, but running `ionic serve --verbose` doesn't seem to offer any useful information.

**Comment by gkappel** [comment]
Also seeing this issue

**Comment by danbucholtz** [comment]
This is fixed in `nightly`.

Thanks,
Dan
