### ISSUE TITLE
AOT issue after upgrade to 2.0.2

### ISSUE THREAD

**Issue by kodeine** [ionic-team/ionic-app-scripts#1112]
#### Short description of the problem:
just upgraded ionic-app-scripts and ionic-angular, added `vendor.js` in index as well but now getting error on AOT which wasnt there on < 2.0.2 of app-scripts. non aot builds with ionic serve is fine.

![image](https://user-images.githubusercontent.com/8620059/28192950-0df48b68-67ff-11e7-8ec4-7240170015e2.png)

**Steps to reproduce:**
1. ionic cordova build android --prod --release

**Which @ionic/app-scripts version are you using?**
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v6.6.0
    OS         : Linux 4.2
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4

**Comment by danbucholtz** [comment]
@kodeine,

How can I recreate this? What angular version do you have?

Thanks,
Dan

**Comment by kodeine** [comment]
@danbucholtz its 4.1.3
```
 "dependencies": {
        "@angular/animations": "4.1.3",
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
```

**Comment by danbucholtz** [comment]
Can you try with `4.0.1` of app-scripts? I am confused, nothing here has changed in a good long while. Can you try with `1.3.12`?
Thanks,
Dan

**Comment by kodeine** [comment]
4.0.1 of app-scripts? or you mean angular?
app-scripts 1.3.12 worked fine earlier, going to try again to be 100%

**Comment by kodeine** [comment]
@danbucholtz 
okay its confirmed, 2.0.2 breaks aot. 

ionic-angular 3.5.2 works fine with app-scripts 1.3.12

**Comment by marcorosi** [comment]
hi, if it can be useful i just upgraded but no issue for me

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v6.10.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by danbucholtz** [comment]
@kodeine,

I think this is an `npm` issue. They have had a ton of issues with `5.0.x` and 5.2.x`. Can you try installing `npm install -g npm@5.1.0`? That seems to be by far the most stable. I am pretty sure this is a lock file issue.

Thanks,
Dan

**Comment by kodeine** [comment]
@danbucholtz 
i've installed npm 5.1.0 and now i am getting this error on ionic serve.

![image](https://user-images.githubusercontent.com/8620059/28249293-75e5b920-6a18-11e7-81ce-e85e05abbc5d.png)

**Comment by kodeine** [comment]
@danbucholtz so it works fine on ionic serve but after build release i see the same error 

![image](https://user-images.githubusercontent.com/8620059/28301415-07c2c368-6b4c-11e7-91d4-0b8225841cd1.png)

it works fine with app-scripts 1.3.12.

**Comment by vkniazeu** [comment]
@kodeine , your `webpackJsonp is not defined` is due to the missing `vendor.js` in your `index.html`.
See https://github.com/ionic-team/ionic-app-scripts/blob/master/CHANGELOG.md#200-2017-07-07

**Comment by kodeine** [comment]
@vkniazeu 
thats how my index.html looks.

```
<body>

<!-- Ionic's root component and where the app will load -->
<ion-app></ion-app>

<!-- The polyfills js is generated during the build process -->
<script src="build/polyfills.js"></script>

<!-- all code from node_modules directory is here -->
<script src="build/vendor.js"></script>

<!-- The bundle js is generated during the build process -->
<script src="build/main.js"></script>

</body>
</html>
```

**Comment by vkniazeu** [comment]
@kodeine hmm... i'd get that error forgetting to add `vendor.js`.
I'm, however, on `npm 5.3.0`.
Try upgrading: `npm i -g npm` - that helped me before with older `ionic-app-scripts` issues.

**Comment by kodeine** [comment]
@vkniazeu just updated to `5.3.0` and same damn issue. i got no idea whats causing this even though everything works fine with app-scripts `1.3.12`

**Comment by vkniazeu** [comment]
@kodeine, are you using `typescript 2.4.1` ? Perhaps, downgrading to `2.3.4` can help?
#1114, #1120 are related to `2.0.2` upgrade, but not sure if they affect this problem.
I've gone down to `2.0.0` for now. Can't give this much more time ATM.

**Comment by kodeine** [comment]
@vkniazeu i've tried with TS `2.3.4` also with app-scripts `2.0.0` same error.
but now i've downgraded app scripts to `1.3.12` and everything works as it should.

**Comment by danbucholtz** [comment]
This seems like a lock file issue to me. How can I recreate? If this was affecting a lot of apps, believe me, we would have heard about it 😸 .

Thanks,
Dan

**Comment by kodeine** [comment]
Give me your email ill allow access to project so you can check it out.

**Comment by danbucholtz** [comment]
Can you recreate in a simple project and upload to github?

Thanks,
Dan

**Comment by kodeine** [comment]
Its already on github but id prefer to keep project private and give u
access. It would be easier to debug this way all u wud do is compile

**Comment by danbucholtz** [comment]
Okay, cool, you should be able to add my username `danbucholtz`.

Thanks,
Dan

**Comment by kodeine** [comment]
Okay give me 1 hr ill go home and add it

**Comment by kodeine** [comment]
@danbucholtz i've given you permissions on the project. Thanks for everything!

**Comment by trebor678** [comment]
Any news on this? I'm having the same problem

**Comment by danbucholtz** [comment]
I haven't had a chance to look yet. @trebor678, are you doing anything interesting with webpack or anything like that?

Thanks,
Dan

**Comment by danbucholtz** [comment]
Sorry, I haven't had a chance yet. It is surprising because nothing with AOT changed in quite a while.

Thanks,
Dan

**Comment by kodeine** [comment]
@danbucholtz i just updated to latest app-scripts and same issue. i'm already pulling off my hair at this point.

**Comment by kodeine** [comment]
@danbucholtz 
so i ran `npm run build --prod` and didnt do the minification etc to debug further. this is what i get after enabling the sourcemaps. `ionic serve` works just fine. 

![image](https://user-images.githubusercontent.com/8620059/28747963-fe5f6ee2-7470-11e7-98a5-72f1755cbbe1.png)

I re-checked the providers, there doesnt seem to be any problem. I'm super confused.

**Comment by kodeine** [comment]
@danbucholtz do you guys offer paid support? i have been trying to resolve this without any luck.

**Comment by kodeine** [comment]
Looks like a angular / webpack bug.
https://github.com/angular/angular-cli/issues/5769

**Comment by kodeine** [comment]
Problem is fixed! =)

It was a circular dependency issue. After installing https://github.com/aackerman/circular-dependency-plugin i was able to figure out what providers were messing up with circular dependencies.

**Comment by darmie** [comment]
@kodeine I am also having this problem, can you explain how you solved it using Circular Dependency Plugin?
