### ISSUE TITLE
Stop build when next file change is observed and start new build immediately

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-app-scripts#1119]
Right now `ionic serve` has to wait for the first build to finish before it triggers a new build when it observes a file change and would therefore trigger a new build. 

With longer build times, this can mean that saving often or recognizing a small mistake and immediately fixing it, has negative effect on the build time. It also causes multiple reloads in the browser until finally the correct version is built and shown.

**Comment by danbucholtz** [comment]
@janpio,

Sorry, I don't think we'll do this. We decided to queue builds up because otherwise a race condition could/would occur. This is the least evil approach. I'm open to suggest on doing this, and would be open to a PR, but this seems non-trivial to me.

Thanks,
Dan

**Comment by janpio** [comment]
I don't see the complexity right now, could you explain what could problems here? The "second" build not building everything needed because it was part of the first one?

**Comment by danbucholtz** [comment]
How would we stop the first build? It's a series of independent asynchronous events. I guess you could check if there is another build in process between each discrete step.

Thanks,
Dan

**Comment by janpio** [comment]
I have no idea how it is implemented, that's why I am asking.

If is all parallel and starting another set of processes would have side effects, having it sequentially seems to be the better way.

(Now that it is faster the impact is smaller anyway)
