### ISSUE TITLE
ionic run --prod --livereload

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic-app-scripts#1121]
#### Short description of the problem:
I'm trying to run an ios app with aot and livereload. Actually it's not working, some files seems missing: 
![image](https://user-images.githubusercontent.com/4112256/28287628-b894da1a-6b3c-11e7-87cb-bbeb4ef4eee4.png)

#### What behavior are you expecting?
It should work. :)

**Steps to reproduce:**
1. `ionic cordova run --livereload --prod`
2. let the app open on iPhone

**Which @ionic/app-scripts version are you using?**
```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : not installed
    npm        : 5.2.0
```

**Comment by danbucholtz** [comment]
Sorry, this is not supported and won't be until Angular gets rid of the JIT compiler.

Thanks,
Dan
