### ISSUE TITLE
[Feature] Multiple times the same components code in bundles using lazy loading

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-app-scripts#1129]
#### Short description of the problem:

When using lazy loading, the code of components end up multiple times in the js bundles.

For example, if I use the same component in Page1 and Page2 I gonna end up with the code of the component in 1.js and 2.js

#### What behavior are you expecting?

The code of the components should only be contained once across all resulting js bundles.

With the introduction of “scope hoisting”, I kind of was hoping that this would have been solve, but seems it isn't yet possible.

This issue was already discussed there but I guess it's good to keep an issue opened about it till solved: https://github.com/ionic-team/ionic-app-scripts/issues/867

Also some forum references:

https://forum.ionicframework.com/t/solved-app-scripts-webpack-scope-hoisting-per-default/98502

https://forum.ionicframework.com/t/app-boot-time-current-state-and-best-practices/80690/17

**Which @ionic/app-scripts version are you using?**

2.0.2

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Unfortunately, this is out of our hands and is actually an issue with webpack. You can customize the `commonChunks` webpack plugin if you want to optimize this as much as possible, but unfortunately we dont have control over the internals of how webpack works.

**Comment by peterpeterparker** [comment]
@jgw96 thx for the answer but don't you think it's good to keep an issue open about that subject till solved? 

I still personally find that's the major reason why I would not use lazy loading of Ionic, so even if it isn't in your hands, it still have major effects on Ionic with lazy loading
