### ISSUE TITLE
Build process hangs until I hit a key in command line

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-app-scripts#1130]
#### Short description of the problem:

Sometimes (yeah, best error description...) the build process seems to just hang and do nothing any more. I notice this when the browser doesn't reload after a few seconds but still shows the black "toast" style bar with "Building...". See the command line output of a recent example:

```
[13:07:17]  build started ...
[13:07:17]  transpile update started ...
[13:07:17]  transpile update finished in 106 ms
[13:07:17]  deeplinks update started ...
[13:07:17]  deeplinks update finished in 26 ms
[13:07:17]  webpack update started ...
[13:07:22]  webpack update finished in 5.42 s
[13:07:48]  build finished in 30.84 s
```

Webpack was already finished at :22, at :48 I then hit the spacebar on the command line and it suddenly finished.

#### What behavior are you expecting?

No hanging.

**Which @ionic/app-scripts version are you using?**

2.0.2

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Command line uses is Powershell.

ionic info:

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : .git android 6.1.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0

**Comment by jgw96** [comment]
Hello @janpio , is there any way that we can reliably reproduce this? I have not seen this on either my windows 10 machine or my macbook, and i run builds a good bit haha.

**Comment by janpio** [comment]
Not really, and I have no idea how I could debug this further. I don't even have any idea how keyboard input on the command line could hav influence on the process running...

It really is just **sometimes** when developing a few days in a row.

**Comment by janpio** [comment]
"Helpful" Windows command line feature: 
https://serverfault.com/questions/204150/sometimes-powershell-stops-sending-output-until-i-press-enter-why
https://stackoverflow.com/questions/591047/command-line-windows-hanging-in-rdp-windows
