### ISSUE TITLE
--consolelogs not working with Genymotion emulators

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic-app-scripts#1133]
`ionic cordova run android -lc` works on a real device, but not on a Genymotion emulator. No logs in the console.

**Comment by jgw96** [comment]
Hello @shawnlan , as this is most likely an issue with the Genymotion emulator and not app-scripts, I am going to close this issue for now. Also, i would recommend updating to the latest version of Android studio and giving the official android emulator a try. It has been GREATLY improved over the last year and a half.
