### ISSUE TITLE
Issue with --prod and --livereload loosing scss dependencies in latest app scripts

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic-app-scripts#1143]
Since upgrading to 2.0.2/ionic 3.5.3 from 3.4.2, SCSS compilation fails when running either of the following two commands:

```
ionic cordova run browser --prod -l
ionic serve --prod
```

Complaining about unknown variables in my app's scss. When I do it without `--prod`, or without the live reload (ie without the `-l` or via an `ionic cordova build browser`) it works fine.

Putting in some debug, I can see that at the end of sass.js's `generateSassData` function when using prod + live reload sassImports is only 5 files, whereas normally it is ~150 files.

**Comment by mhartington** [comment]
1) Do not use cordova-browser, at all. It was an experimental platform from cordova that is broken.

2) Unfortunately you can't have watch (live-reload/serve) running and still do a production build, so this is to be expected.

I'm not sure if we'll be adding this to be honest, maybe @danbucholtz would know the best.

**Comment by danbucholtz** [comment]
We have no plans on adding support for a live reloading prod build.

With Angular 5, all builds will in theory be prod builds.

Thanks,
Dan
