### ISSUE TITLE
Getting source-maps with --prod build?

### ISSUE THREAD

**Issue by christoffer-Van** [ionic-team/ionic-app-scripts#1190]
#### Short description of the problem:
Currently using Sentry for error reporting, and I'm having trouble with my source-maps. I've noticed the main.map.js is removed from the www/build file on --prod builds. I believe I need them to be in the build so I can upload them, so all the paths still match up?

#### What behavior are you expecting?
I understand source-maps are stripped to reduce the app size. Is it possible however to have them spit out into a different folder rather than deleted towards the end of the build, so they can be uploaded to Sentry?

**Steps to reproduce:**
1. `ionic cordova build android --prod`
2. No source maps in www/build

**Which @ionic/app-scripts version are you using?**
2.1.4

**Comment by christoffer-Van** [comment]
Seems to have figured this out myself.

`"ionic_generate_source_map": "true"` added to `config {}` in package.json

**Comment by Xample** [comment]
did you mean ```ionic.config.json``` ?

**Comment by stevecarlton** [comment]
@Xample yes I believe he did. I added `"ionic_generate_source_map": "true"` to `ionic.config.json` and source maps were generated when using --prod.

**Comment by stevecarlton** [comment]
@Xample Actually, it needs to be added to the main project's `package.json` as
`    "config": {
    "ionic_generate_source_map": "true"
    },
`
