### ISSUE TITLE
.sourcemaps folder

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-app-scripts#1216]
#### Short description of the problem:

When I serve my ionic app, it creates a `.sourcemaps` folder in the project root.

#### What behavior are you expecting?

Ionic shouldn't pollute my project root with sourcemaps or any generated files.

**Steps to reproduce:**

1. `ionic start testApp blank`
2. `cd testApp`
3. `npm run ionic:serve`
4. `ls .sourcemaps` (contains `main.css.map` and `main.js.map`)

**Which @ionic/app-scripts version are you using?**

`2.1.4`

**Comment by Sneko** [comment]
@jgw96 @mlynch same for me and 16 other people.

I'm using the following version of ionic-app-scripts: 3.0.1

**Comment by mlynch** [comment]
I don’t see a better place for them. Now you have prod sourcemaps instead of us deleting them. There’s a flag to disable it (can dig up later)

Add .sourcemaps to your .gitignore to avoid checking them in.

**Comment by simonhaenisch** [comment]
How about `/tmp` or `$TMPDIR` on macOS, both should get cleaned up by the system (see <https://apple.stackexchange.com/a/22716/229133>). On Windows, I think the equivalent would be `%TEMP%` or `Path.GetTempPath()` (<https://msdn.microsoft.com/en-us/library/system.io.path.gettemppath.aspx>), which would usually be something like `C:\Users\UserName\AppData\Local\Temp\`.

Operating systems provide temporary folders exactly for cases like that. Please re-open this as it is not solved, and thanks for looking into it 🤓

**Comment by mlynch** [comment]
I'm unsure if people want the sourcemaps to optionally commit them to source code management. They are useful in many cases. We're using them for Ionic Pro monitoring, for example.

**Comment by simonhaenisch** [comment]
Then how about making an option `sourcemapsDir` in `ionic-config.json` in case people want it (I guess many only need them temporarily for debugging)?

**Comment by joeystandrew** [comment]
Yeah, would love for this to be a configurable option inside package.json "configs" section.

**Comment by simonhaenisch** [comment]
@mlynch do you want to reopen this?
