### ISSUE TITLE
Font not Found - ionic v3

### ISSUE THREAD

**Issue by Barathwaja** [ionic-team/ionic-app-scripts#1228]
**Roboto Fonts** are missing in **build/assets/fonts** folder , because of that it affects debug and prod too.

_using Ionic CLI : 3.10.3_

![error](https://user-images.githubusercontent.com/5066436/30560233-e82d914e-9cd4-11e7-8ef2-1ce50b3ab937.png)

**Comment by numerized** [comment]
+1 guys I have same problem since upgrade

**Comment by danbucholtz** [comment]
This should be fixed now.

Thanks,
Dan

**Comment by NiklasMerz** [comment]
@danbucholtz Is this fixed in version 3.0.0? I am having this problem with the latest app scripts only in **prod mode**.

Thank you,
Niklas

**Comment by numerized** [comment]
It works here, even in --prod mode.
Thanks

**Comment by MELAS007** [comment]
how can i solve this issue?

**Comment by Barathwaja** [comment]
is issue solved??
