### ISSUE TITLE
Wrong source maps in production builds using UglifyJS

### ISSUE THREAD

**Issue by ionut-movila** [ionic-team/ionic-app-scripts#1232]
#### Short description of the problem:

On production builds, using flag `--prod` I get source maps that map transpiled JS code instead of original TS code. This is needed for Sentry monitoring, in order to get a proper stack trace from TS.

#### What behavior are you expecting?

Generated maps from transpiled code pointing to TS code should not be overridden by UglifyJS but instead "merged". Maybe use something like https://github.com/jvilk/merge-source-maps ?

**Steps to reproduce:**
1. Run `ionic cordova build android --prod`. The output source maps DO NOT keep reference to TS code
2. Run `ionic cordova build android`. Now the uglify task named `minify` is not executed and source maps DO keep the reference to original TS code.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
```
@ionic/app-scripts : 2.1.4
@ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3
```

**Comment by danbucholtz** [comment]
This should be resolved now.

Thanks,
Dan
