### ISSUE TITLE
Problems with JDK9?

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-app-scripts#1237]
_From @arthurflor on September 22, 2017 12:21_

**Ionic version:**
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
Recentemente atualizei o JDK para a versão 9 e desde então a criação de apk retorna o erro:
```
Requirements check failed for JDK 1.8 or greater.
```

Retorno do java -version: 
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Expected behavior:**
APK creation

**SIfteps to reproduce:**
The command:
```
ionic cordova build android --prod --release
```
**Other information:**
It's real problem from the ionic? Other softwares doesn't any problem with the new version.

**Ionic info:**

```
cli packages:

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.5.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v8.5.0
    npm               : 5.4.2 
    OS                : Linux 4.12

Misc:

    backend : legacy
```

_Copied from original issue: ionic-team/ionic#12954_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

As this appears to be an issue with Ionic App Scripts and not with the Ionic Framework, I will move this issue to https://github.com/ionic-team/ionic-app-scripts. Please follow the issue over and provide any further feedback or information over there.

Thank you for using Ionic

**Comment by vazad28** [comment]
I got the new macbook and installed sdk-9 as instructed and stuck with this same issue.

**Comment by danielsogl** [comment]
The Android SDK don't support Java 9. downgrade to 8

**Comment by danbucholtz** [comment]
This doesn't seem to be an app-scripts issue.

Thanks @danielsogl.

Thanks,
Dan

**Comment by shadowfoxish** [comment]
@danielsogl Perhaps it would be good to remove the instruction from the docs about using it then?

http://ionicframework.com/docs/v1/guide/installation.html

> Install the most recent Java JDK (NOT just the JRE).

**Comment by tvsijin** [comment]
I am using Android Studio for a while now, and i dont remember installing jdk 8..  The Android SDK still don't support Java 9?

**Comment by Noble-Shiva** [comment]
Hi All,

I had the same issue, while running cordova build.

java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

I have uninstalled Java JDK 9 and installed JDK 1.8, fixed the problem.

**Comment by mindaccentin** [comment]
I fixed the issue by uninstalled Java JDK 9 and installed JDK 1.8. 
After this I got gradle issue in mac. Fixed that gradle issue as per the instruction in following
https://kodejava.org/how-do-i-install-gradle-in-os-x/

**Comment by climbican** [comment]
What, you have to go all the way back from 9 to 1.8 for it to work??? Does anyone else consider this a bit ridiculous?

**Comment by audacitus** [comment]
@climbican I think the numbering is a bit strange:
searches for JDK 1.8 point to JDK 8 (and so on)

Installed JDK 10 and had this error. currently downgrading. will update when done.

**Comment by crashforce** [comment]
I'm on a Mojave MAC...
![captura de tela 2018-10-30 as 22 29 52](https://user-images.githubusercontent.com/8712152/47760573-b03ea980-dc93-11e8-8f9a-edd8412bfde4.png)

I'm having the same error, but my JDK version is the newest one (Version 11.0.1).

I will see if I install version 8 and test if the problem is solved.

**Comment by crashforce** [comment]
Actually, after deleting the newer version of JDK and installing version 8 the problem has been solved. We are waiting for the new version .. Meanwhile we are using this same one that has no error.
