### ISSUE TITLE
ionic build --prod Unexpected token <

### ISSUE THREAD

**Issue by Hezier1223** [ionic-team/ionic-app-scripts#1241]
yesterday，i update ionic CLI to the version 3.12.0 ,then when i use ionic build --prod ,it appears the the following error :Unexpected token <; And i run with the same error in my another angular project ,but none has replied me , thanks a lot

**Comment by dani-inside** [comment]
Same here. 

**Build command**
ionic cordova build ios --prod

**Output**
```
Error: Uglify failed: Unexpected token operator «=», expected punc «,» in undefined at line undefined, col undefined, pos undefined
    at new BuildError (/Users/user/ionic-app/sources/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (/Users/user/ionic-app/sources/node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at /Users/user/ionic-app/sources/node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
```

**Version and system information**
Ionic CLI: 3.12.0
ionic-app-scripts: 2.1.4
ionic-angular: 3.6.1

**Comment by danbucholtz** [comment]
Sorry, I'm not sure. Please create a new issue with a project to recreate the issue.

Thanks,
Dan
