### ISSUE TITLE
Ionic build --prod issue

### ISSUE THREAD

**Issue by chris-eduardo** [ionic-team/ionic-app-scripts#1242]
ionic cordova build android --prod

Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/database' in '/Users/chris/GIT/ccoocat/src/app'
resolve '../../angularfire2/database' in '...../src/app'
  using description file: ...../package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: ...../package.json (relative path: ./src/app)
    using description file: ...../package.json (relative path: ./angularfire2/database)
      no extension
...

ng version
angular-cli: 1.0.0-beta.28.3
node: 8.3.0
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3

ionic version
3.12.0

node -v
v8.3.0

npm -v
5.4.2

cordova -v
7.0.1

angularfire2 4.0.0-rc.2

don't works
angularfire2 4.0.0-rc.1
angularfire2 4.0.0-rc.0

building with --dev works well

**Comment by danbucholtz** [comment]
This is an issue with angular I believe. I think it is fixed now. Please let me know if this doesn't work with the latest angular/ionic.

Thanks,
Dan
