### ISSUE TITLE
Can't run build for legacy 1.3.3 app

### ISSUE THREAD

**Issue by adyngom** [ionic-team/ionic-app-scripts#1244]
#### Short description of the problem:
I cannot get beyond the build step of trying to run a legacy client app using the ionic cli

#### What behavior are you expecting?
The normal build firing a de server and pointing to a local url for developemt

**Steps to reproduce:**
1. npm install -g ionic@1.3.3
2. rm -rf node_modules
3. npm install
4. ionic serve

```sh
Running 'serve:before' gulp task before serve
[11:12:43] Starting 'sass'...
Caught exception:
 Error: Missing error message
    at new PluginError (/Users/adyngom/Code/IonicProjects/weli/node_modules/gulp-util/lib/PluginError.js:53:28)
    at DestroyableTransform.logError (/Users/adyngom/Code/IonicProjects/weli/node_modules/gulp-sass/index.js:179:17)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at onwriteError (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:427:12)
    at onwrite (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:3)
    at TransformState.afterTransform (/Users/adyngom/Code/IonicProjects/weli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at errorM (/Users/adyngom/Code/IonicProjects/weli/node_modules/gulp-sass/index.js:134:14) 
```

**Comment by rasor** [comment]
@adyngom:
I just had a similar problem with node_modules/node-sass/.
@ionic/app-scripts was using a version of node-sass that did not support the new Node v8.
If your Node.js is too new you can back to an older
Or you can use a newer version of @ionic/app-scripts.
Perhaps solution is same in you case.
Or how about creating a new starter and move the code from your legacy app?

**Comment by adyngom** [comment]
@rasor thanks for responding. When you say move legacy to new starter what do you essentially move?? The old www folder replaces the new one I guess - and what else

**Comment by adyngom** [comment]
@rasor after this update:
```
npm install @ionic/app-scripts@latest --save-dev
```
and running 
```
ionic serve
```
the error above disappears and the servers launch but now it complains about missing **ionic.bundle.js**

**Comment by rasor** [comment]
@adyngom - i just realized that your case is much different, since in Ionic1 `gulp` is used instead of `@ionic/app-scripts`, which is Ionic 2 or more.

So instead I created a new ionic1 project
```
ionic start weliupdate blank --type=ionic1
cd weliupdate
ionic serve
```
This gives
```yaml
  "devDependencies": {
    "gulp": "^3.5.6",
    "gulp-clean-css": "^3.7.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^3.1.0"
  }
```
Does such new project run without errors?
If yes, then you have a template you can move your code into. And perhaps you can just use these versions in your original project.

**Comment by adyngom** [comment]
@rasor yes this runs indeed with the following package.json
```javascript
{
  "name": "weliupdate",
  "version": "1.1.1",
  "description": "weliupdate: An Ionic project",
  "devDependencies": {
    "gulp": "^3.5.6",
    "gulp-clean-css": "^3.7.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^3.1.0"
  },
  "dependencies": {
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.1",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic-plugin-keyboard": "^2.2.1"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-console": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "ionic-plugin-keyboard": {}
    }
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ]
}
```

I'm going to try to move files over, so it should essentially be whatever is in the old ```www``` to replace the new one??

Thanks for helping with this :)

**Comment by rasor** [comment]
@adyngom Nice that I could help.
Yes - hopefully all will just work after move of www

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This issue is being moved to the CLI repo. Please follow and respond to the new issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2795
