### ISSUE TITLE
[3.0.0] JavaScript heap out of memory

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-app-scripts#1247]
#### Short description of the problem:

With the update to version `3.0.0`of app-scripts I'm facing the error `JavaScript heap out of memory` when I run the cmd `ionic cordova build ios --prod`

#### What behavior are you expecting?

No heap exception. 

There are currently a couple of opened issues about this, after discussing it on the forum, we thought that it would be a good idea to report it too since I'm only facing it after the update of app-scripts. I rolled back to version `2.1.4` where I don't face that problem.

Also I could confirm that the workaround/solution described by @epetre in issue #1076, respectively giving `node` more memory by setting for example `--max-old-space-size=8192` let me built my app with app-scripts `3.0.0` without facing the heap error

Opened issues:

#1125 
#1076 
#1036

Forum:

https://forum.ionicframework.com/t/3-7-0-ios-build-with-prod-not-working/107061

A similar issue on the angular-cli:

https://github.com/angular/angular-cli/issues/5618

**Steps to reproduce:**
1. Find a not small app
2. Use app-scripts `3.0.0`

**Which @ionic/app-scripts version are you using?**

cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.0
    Ionic Framework    : ionic-angular 3.7.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v8.5.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy

**Comment by danbucholtz** [comment]
Node just has really low memory defaults :(

Try this once:

```
node --max-old-space-size=4096 $(which ionic) cordova build --prod
```

This is sort of an ugly command. I am not sure what we can do to simplify it, though.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
thx @danbucholtz your cmd do the tricks respectively 

    node --max-old-space-size=4096 /usr/local/bin/ionic cordova build ios --prod

It looks like `max-old-space-size` is definitely the solution.

This was pointed out by @epetre in issue #1076 but even if you think your cmd is "ugly", the good point is that it's only one cmd and that it don't need modifications in package.json 👍 

Should I close the issue or keep it open till someday there is a solution (from node side or web pack side)?

**Comment by danbucholtz** [comment]
We are looking at ways to mitigate this on our end. I'll keep you posted.

Thanks,
Dan

**Comment by Vishal-Isharani** [comment]
i'm also facing this error while doing `ionic serve`
  

```
 @ionic/cli-utils  : 1.12.0
 ionic (Ionic CLI) : 3.12.0
 @ionic/app-scripts : 3.0.0
 Cordova Platforms  : android 6.2.3
 Ionic Framework    : ionic-angular 3.6.1
 Node              : v8.4.0
 npm               : 5.4.2
 OS                : Windows 10
```

**Comment by Lingomat** [comment]
I've had this memory problem pop up frequently. My app is fairly large. Increasing node memory seems to be fixing a symptom which is intermittent. It's often turned out to be related to the version of typescript (also maximum call stack size). Right now, my app builds on ts 2.3.4 with no memory boost, in dev and prod.

I wonder if there's a clue by looking at the bundle?

**Comment by danbucholtz** [comment]
It really just has to do with how many files are loaded into memory, and then probably something with `ngo`. I'm not sure, I haven't profiled it. It doesn't happen in most apps so the number of files loaded into memory must be sufficiently high. It is unfortunate that Node has such low default limits in my opinion.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
Today I updated my node@8.7.0 and npm@5.5.1 and it seems that I don't know face the problem anymore

@danbucholtz should I close this ticket, since I created it, or are you working on that?

**Comment by Vishal-Isharani** [comment]
@peterpeterparker i also updated my node@8.7.0 and npm@5.5.1 but i'm still facing this error 
i'm not able to run `ionic serve`

**Comment by peterpeterparker** [comment]
@Vishal-Isharani thx for checking it, then maybe I'm just lucky, weird

**Comment by sharonswli** [comment]
I had the same issue. Tried allocating 8gbs to node with `node --max-old-space-size=8192` but the `--prod` building is still failing. We have a large app with 500+ components, but we never had trouble building prod/AOT with app-scripts `1.3.7`(webpack 2), so I'm inclined to believe it's a memory leak coming from webpack 3 that's used by the the newest version of ionic-app-scripts. 

I really hope this issue will be seriously looked at by the @ionic team so larger apps can remain supported by future releases and updates.

**Comment by bkarv** [comment]
Similar to sharonswli  we have reasonably large app with 50+ components. We can run ionic serve but unable to run the production build, getting out of memory issue. It seems like there a few open tickets related to this issue but no definite resolution. It is a bit worrisome that Ionic is unable to handle larger apps.....

**Comment by peterpeterparker** [comment]
@sharonswli I see that you are using node `v6`, have you try to build your app with a more actual version of node like `v8` in combination with the `--max-old-space-size=8192` flag? 

p.s.: more than >500 components?  that's definitely an app I would love to try :)

@bkarv just checked my app, I have 56 components and 32 pages and I'm able to build it with the `--prod` flag. what are your `ionic info`, are you up-to-date with everything?

I opened this issue because I was facing the problem, temporary my problem was solved using `--max-old-space-size=4096` but like I staten above, at some point the problem disappeared, not sure if it's linked with the node/npm update I run. What's sure it's that I'm update-to-date with all libs.

**Comment by bkarv** [comment]
@peterpeterparker thanks after weeks of trying I literally just finally got my app doing a production build. 

First I increased my memory thanks to ValterSantosMatos post in https://github.com/ionic-team/ionic-app-scripts/issues/1036. This then showed an error due to rxjs _"Cannot read property 'type' of undefined"_   I assume this was the issue causing the memory leak in the first place. I fixed this by upgrading to typescript 2.6.1.

So this may not work for everyone one else but these are the step I did to get it working:

1. Upgraded to Ionic to 3.9.2 and latest Ionic Cli and scripts (see Ionic Info below)
2. Ran 'ionic doctor check' and did the suggested upgrades
3.  Increased my memory for the build by adding this to the package.json to scripts section:
```
"ionic:build": "node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build",
```

4. Updated typescript to 2.6.1 by doing  
`npm typescript@latest`

5. Ran` npm run ionic:build --prod`

Here is my ionic info it helps:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.1.2 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.1 
    Node       : v8.6.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by peterpeterparker** [comment]
@bkarv congrats and pretty cool to describe the details!

**Comment by sharonswli** [comment]
@bkarv good to hear! How long do your prod builds take now after such changes? I also followed the memory increase solution in [#1036](https://github.com/ionic-team/ionic-app-scripts/issues/1036) and eventually got a successful build. There are no errors however, and build time still exceeds 30+ minutes.

**Comment by bkarv** [comment]
@sharonswli 30+ minues seems a long time but then again there are so many variables at play. It takes me about 7mins. To  compare size my final www file is about 7.5mb. My comp is 3.3Ghz Intel Core i5 w/ 16Gb kaby lake.

**Comment by Sprauch** [comment]
This may have been fixed in Webpack 3.9.0, where they noticed that the ConcatenatedModules were traversing an incremental list of super long strings for each module concatenated. This is likely why only projects with plenty of modules are suffering. 
(specific fix: https://github.com/webpack/webpack/pull/5997)

Would be nice if ionic-app-scripts dependencies could be updated to support that version. 

Worth mentioning for context is that my build times increased from about 15 minutes to 5 hours after upgrading the webpack from 2.4.1 to 3.8.1, and I had to do the workaround with heap space allocation to even get a build through.

**Comment by nvirth** [comment]
> node --max-old-space-size=4096 /usr/local/bin/ionic cordova build ios --prod

How can I run this on windows?
I've tried to put the win full path (which is C:/Users/{UserName}/AppData/Roaming/npm/ionic[.cmd] by me) into the above one, in place of the linux full path, but it did not work,

I also tried the package.json solutions mentioned above, like:

> "ionic:build": "node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build"

This also works on windows, but the command I need to run with 8GB memory is:

> ionic cordova **run** android

And there seems to be no "run" command in ionic-app-scripts

**Comment by Sprauch** [comment]
@nvirth the easiest way to run this on windows would be to add the line:
```
"scripts": {
    "ionic:build": "node --max-old-space-size=8192 --stack-size=1968 node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build"
  },
```
into the package.json which you've already mentioned, and then run the command
`npm run ionic:build --prod` inside your project folder, from a terminal prompt

At least that did the trick for me.

**Comment by andrefa** [comment]
How can I run it on my CI env? I'm pretty sure I do not have power over memory allocation there. I'm using NeverCode for mobile builds currently.

**Comment by ericmulcahy** [comment]
Any updates on this? The workaround does not work for me. The build takes > 4 hours on a Mac with --max-old-space-size=12000 then fails out of memory. On a WIndows machine it is the same thing with --max-old-space-size=20000. 

Is it possible to update to Webpack 3.9.0 (which presumably fixes this)? My Ionic info is in the closed thread just above.

**Comment by ChargerIIC** [comment]
As a test I installed webpack 3.11.0 manually to see if the aforementioned webpack patch was a solution. Unfortunately there is no change. I've been able to allocate as much as 8 gigs of RAM to the process, but it still never finishes.

I only have 6 pages and 2 components. I'm wondering if there is some kind of common trait that is causing the slowdown. I have much larger Ionic projects that compile fine and the issue seems to only occur when compiling for web.

**Comment by ericmulcahy** [comment]
@ChargerIIC I checked out the source code you linked in the other thread, and I see you're using Firebase with AngularFire. I am also using that in my project. Maybe that is the common link?

Although the prod build was working fine for me for 2 months before it started failing, and I was using AngularFire the whole time, so who knows.

**Comment by bkarv** [comment]
@ChargerIIC @ericmulcahy Would it be worthwhile running the prod build without Firebase and AngularFire imported and see if it compiles to pinpoint the source of the error?

**Comment by Lingomat** [comment]
Having had this problem myself, the one thing I found that reliably caused the problem was using older versions of Typescript.

**Comment by ChargerIIC** [comment]
@bkarv Unfortunately, that didn't resolve the issue. Webpack took longer to finish (probably because I blew a hole in the old dependency graph), but still didn't transition to the node-sass step.

I'm about 20 minutes in, but it looks like the typescript upgrade to 2.9.2 didn't resolve the issue. I've also commented out all empty SCSS objects (like the ones you get when you generate a new component/page.

Going to let this chunk away and then re-attempt a node-sass upgrade if it fails again.

**Comment by Lingomat** [comment]
@ChargerIIC I modified your repo to remove the abomination of AngularFire and sure enough, it compiles --prod no problem (42 seconds). To be fair, I had to comment out a fair bit but I really doubt that was your problem. AngularFire has deps of a different angular and rxjs than the one you're using.
It doesn't even do anything you can't implement in short functions directly from the firebase js API in my opinion...

**Comment by ericmulcahy** [comment]
Thanks @Lingomat, I will try removing AngularFire, although this will be more of an undertaking for my project.

**Comment by pavel-zdenek** [comment]
This is happening to me on a particular project when ionic@4.0.0 is installed. Downgrading to 3.20.0 makes the OOM go away. Looks like a regression with major version(s).

**Comment by liangwenzhong** [comment]
any solution to this?

**Comment by lordgreg** [comment]
Well... just started happening to me too. Windows. Still no solution.

**Comment by basvdijk** [comment]
I've found a solution when using Ionic which was pointed out in an old message on the forum: https://forum.ionicframework.com/t/3-7-0-ios-build-with-prod-not-working/107061/24

Open `node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js`

Change the first line from:
`#!/usr/bin/env node`
into
`#!/usr/bin/env node --max-old-space-size=4096`

I tried values 1024 and 2048, but for my relatively large app I needed 4096.

Now I am able to run `ionic cordova build android --prod --release` with out the `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` error.

**Comment by peterpeterparker** [comment]
Just noticed that I'm the OP of this issue therefore I gonna allow my self to close it. Firstly I didn't faced the problem anymore since the 14 Oct 2017 (see my above msgs), secondly I have migrated my app to Ionic v4 where `ionic-app-scripts` isn't use anymore

**Comment by zakton5** [comment]
For any future readers, my issue is that I had the firebase (5.5.3) package installed and did not properly import the specific modules. The fix is shown here: [#848](https://github.com/firebase/firebase-js-sdk/issues/848). I guess importing everything was much too large.

**Comment by kirillgroshkov** [comment]
Found a better solution, to specify NODE env variable before the build: `export NODE_OPTIONS=--max-old-space-size=4096`

Credits to: https://stackoverflow.com/a/48895989/4919972

**Comment by adil-Pathan** [comment]
I found a better solution just Now. Set environment variable NODE_OPTIONS with value as --max_old_space_size=4096  Also make sure that environment variable _JAVA_OPTIONS with value as -Xmx1024M is also set.  My machine has Windows 7 ( 32 bit ) and 4GB RAM.

> **Happy coading**
