### ISSUE TITLE
New package.json dependencies after build

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic-app-scripts#1248]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
After the build process, all the cordova dependencies are added to the `dependencies` list of my `package.json`. This did not happen in version `2.1.4`, and I don't see why I would need to install `ionic-plugin-keyboard` (for example) as a npm dependency

Now I have in `package.json`:
```
"dependencies": {
        ...
        "cordova-android": "~6.1.2",
        "cordova-ios": "~4.3.1",
        "cordova-browser": "~4.1.0",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-geolocation": "~2.4.3",
        "cordova-plugin-splashscreen": "~4.0.1",
        "cordova-plugin-statusbar": "2.2.1",
        "cordova-plugin-whitelist": "1.3.1",
        "ionic-plugin-keyboard": "~2.2.1"
}
```

Also, side note, it is very annoying that the formatting is 4 spaces instead of 2

**Which @ionic/app-scripts version are you using?**
3.0.0

**Comment by vknabel** [comment]
@mebibou Did you upgrade your cordova? That's the new behavior of `cordova prepare` since [Cordova 7.0.0](https://cordova.apache.org/news/2017/05/04/cordova-7.html)

**Comment by mebibou** [comment]
@vknabel oh yes I did, well spotted. How do you turn this off?

**Comment by danbucholtz** [comment]
This is how cordova will manage things going forward. Nothing we can do about it unfortunately. This is ultimately a good change in my opinion.

Thanks,
Dan
