### ISSUE TITLE
App script 3.0.0 uglifyjs message in cli

### ISSUE THREAD

**Issue by vksgautam1** [ionic-team/ionic-app-scripts#1250]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
in app build it is showing this
“[14:22:23] uglifyjs started …” 
message displaying instead of  "uglifyes"

#### What behavior are you expecting?
 uglifyes started …” 

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.0

System:

    Android SDK Tools : 25.2.5
    Node              : v7.10.0
    npm               : 4.2.0
    OS                : Windows 10

Misc:

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
I just fixed this. It'll ship soon.

Thanks,
Dan
