### ISSUE TITLE
`ionic build` fails without @angular/tsc-wrapped - 3.0.0

### ISSUE THREAD

**Issue by gianpaj** [ionic-team/ionic-app-scripts#1252]
#### Short description of the problem:
```
$ ionic build
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:6:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Steps to reproduce:**
1. update ionic-app-scripts to 3.0.0
2. update ionic-angular to 3.7.1
3. update `webpack.config.js` ([link](https://github.com/ionic-team/ionic-app-scripts/blob/master/config/webpack.config.js)) as suggested from changelog breaking changes

```
$ ionic info

cli packages: (.../node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.8.6
    ios-sim           : 5.0.8
    Node              : v6.11.3
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy
```

**Which @ionic/app-scripts version are you using?**
3.0.0.

**Workaround**
Installing `@angular/tsc-wrapped` in the mobile app project fixes the issue

**Comment by danbucholtz** [comment]
@gianpaj,

Interesting. `@angular/tsc-wrapped` is a private dependency for angular, so you shouldn't have to install it. That is very interesting. Could you try blowing away your lock file and trying again?

Thanks,
Dan

**Comment by gianpaj** [comment]
I removed the `package-lock.json` file, ran `npm i` but `ionic build` still fails with the same err msg.

Here is the diff between the package-lock json before and after (if helps the diagnostic):
https://gist.github.com/gianpaj/581130392676756339962a1c88f306a7

**Comment by scottbcovert** [comment]
@gianpaj I realize how nuanced these issues can be so YMMV, but FWIW I had the same error and noticed npm displaying a warning regarding an unmet peer dependency on typescript@^2.1.5 by tsc-wrapped so I ran ```npm install typescript@^2.1.5 --save-dev``` and that resolved the problem for me

**Comment by danbucholtz** [comment]
Hmm, okay I am not sure. This seems like a one-off thing. Anyone have any information on how to solve? I don't think this is too widespread or there would be many more reports.

Thanks,
Dan

**Comment by gianpaj** [comment]
Yeah not sure what happened. I had other issues with cordova plugins so I reverted back a bunch of changes in package.json and config.xml and now i have a semi-stable build and app.

I'll reopen this if I see this again once I upgrade back to 3.0.0

Cheers
