### ISSUE TITLE
Styles are missing from custom component when built with --prod

### ISSUE THREAD

**Issue by sean-hill** [ionic-team/ionic-app-scripts#1254]
#### Short description of the problem:

When building with the `--prod` file, `ion2-calendar`'s styles are missing from the build.

#### What behavior are you expecting?

I expect the styles of `ion2-calendar` to be in the built `CSS` file like they are when run with `ionic serve`.

**Steps to reproduce:**

[Here is the issue](https://github.com/HsuanXyz/ion2-calendar/issues/73) on the `ion2-calendar` which includes a sample repository and replication steps.

**Comment by danbucholtz** [comment]
Can you do me a favor and create a super simple example project to demostrate the issue?

I think I'll be able to fix it.

Thanks,
Dan

**Comment by Artfloriani** [comment]
@danbucholtz An example project was posted in the issue linked by @sean-hill. I am also facing this issue on my project.

Here is the link for the example project posted on the issue: https://github.com/sean-hill/ion2-calendar-prod-build-bug

**Comment by danbucholtz** [comment]
Found the bug. We'll fix. Here's a short term fix:

1. Open `node_modules/@ionic/app-scripts/dist/webpack.js
2. Go to line 88
3. 
```
    //if (!context.isProd || !context.optimizeJs) {
        var files_1 = [];
        stats.compilation.modules.forEach(function (webpackModule) {
            if (webpackModule.resource) {
                files_1.push(webpackModule.resource);
            }
            else if (webpackModule.context) {
                files_1.push(webpackModule.context);
            }
            else if (webpackModule.fileDependencies) {
                webpackModule.fileDependencies.forEach(function (filePath) {
                    files_1.push(filePath);
                });
            }
        });
        var trimmedFiles = files_1.filter(function (file) { return file && file.length > 0; });
        trimmedFiles.forEach(file => console.log('file: ', file));
        context.moduleFiles = trimmedFiles;
    //}
```

Comment out the `//if (!context.isProd || !context.optimizeJs) {` and the closing bracket at the bottom.

This should work for you. We will push out a fix ASAP. Probably early next week. Depends on when my wife has a baby that is due any day now 🐱 

Thanks,
Dan

**Comment by danbucholtz** [comment]
Scratch that. Just do this:

```
npm install @ionic/app-scripts@nightly
```

Thanks,
Dan

**Comment by Artfloriani** [comment]
On my project it is still breaking. Only the --prod build
