### ISSUE TITLE
v3.0.0.don't bind css files to its loader

### ISSUE THREAD

**Issue by anxorl** [ionic-team/ionic-app-scripts#1259]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
v3.0.0.don't bind css files to its loader

#### What behavior are you expecting?
.css extension isn't bind to its bundler and throw the error
Error: ./*.css Module parse failed:
            /path/*.css Unexpected
            token (3:0) You may need an appropriate loader to handle this file type.

Versioin 2.4.1 imports it as it is expected

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
3.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
Can you explain to me what the issue is here? We have never supported importing `css`.

Thanks,
Dan

**Comment by anxorl** [comment]
I want to import css from custom module. I have this code in the main module of my app

import 'ng-ver-malla/dist/visor-mallas.css'

I have modified webpack.config.js adding this lines in loaders section

      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },

This import css file and insert it in the final webpack bundle.
Version 2.4.1 and previous do this as it is expected, Version 3.0.0 fails with the message shown in the previous post.
css-loader is correctly installed but .css files are not binding to correspondant loader.
Versions of both webpack and css-loader are fixed between ionic-scripts versions.

**Comment by danbucholtz** [comment]
Hmm, sorry I'm not sure. It is hard for us to debug custom configurations. Can you just use the copy config to move the css file to `www/assets` or something?

Thanks,
Dan

**Comment by danbucholtz** [comment]
Due to lack of activity, we're closing this issue.

Thanks,
Dan
