### ISSUE TITLE
Hook in Prepare Step gets executed twice

### ISSUE THREAD

**Issue by TheHighriser** [ionic-team/ionic-app-scripts#1262]
#### Short description of the problem: 

I have a hook running the after_prepare step. It gets executed twice when I use ionic cordova run android. If I only use cordova run android it works.

#### What behavior are you expecting?

That my hook gets executed only once.

**Steps to reproduce:**
1. Create a Plugin which uses Hook in the after_prepare step
2. Do ionic cordova run android
3. Step gets executed twice

**Which @ionic/app-scripts version are you using?**
2.1.3

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This issue is being moved to the CLI repo. Please follow the issue over there.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-cli#2796
