### ISSUE TITLE
App importing node file-type fails to start using 3.0.0 on iOS device with --prod

### ISSUE THREAD

**Issue by saschwarz** [ionic-team/ionic-app-scripts#1269]
#### Short description of the problem:
An app importing the file-type node module using `import * as` no longer starts JS code when using ionic-app-scripts version 3.0.0 **only** when run on a physical iOS device and compiled with `--prod`.

#### What behavior are you expecting?

App should start/splash screen close.

**Steps to reproduce:**
1. `ionic start app blank`
2. `npm install file-type @types/file-type --save`
3. Edit `home.ts` as follows:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import * as FileType from 'file-type';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  constructor(public navCtrl: NavController) {
    console.log(JSON.stringify(FileType));
  }
}
```
4. Connect a physical iOS device via USB.
5. `ionic cordova run ios --prod`

If you downgrade to `@ionic/app-scripts: "2.1.4"` the app will run correctly.

**Which @ionic/app-scripts version are you using?**
3.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
I'm not seeing that behavior.

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import * as FileType from 'file-type';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {
    console.log('FileType: ', FileType);
  }

}
```

Works correctly for me on a prod build.

Please let me know if there is something else I can help you with.

Thanks,
Dan

**Comment by saschwarz** [comment]
I just re-re-checked and it's 100% repeatable for me on both of my iOS devices... 
Here's my `ionic info`:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v7.4.0
    npm        : 4.0.5 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```

**Comment by saschwarz** [comment]
@danbucholtz please let me know what versions you used to test this? I can only make it work on the physical devices using 2.1.4
