### ISSUE TITLE
Readme is out of date for version 3.0.0

### ISSUE THREAD

**Issue by racedale** [ionic-team/ionic-app-scripts#1270]
#### Short description of the problem:
Readme still references rollup config, even though that was removed with version 3.0.0 in favor of webpack. 

**Steps to reproduce:**
1. View the readme in the root folder

**Which @ionic/app-scripts version are you using?**
3.0.0

**Comment by danbucholtz** [comment]
Thanks, I've updated it and will push shortly.

Thanks,
Dan
