### ISSUE TITLE
"Cordova is not available" when running in web browser

### ISSUE THREAD

**Issue by klauserber** [ionic-team/ionic-app-scripts#1289]
#### Short description of the problem:
Hi, I am here on ionic-cli 3.13.2 and see the following warnings:

...
[14:23:25]  console.log: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[14:23:26]  console.warn: Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
[14:23:26]  console.warn: Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
[14:23:29]  lint finished in 5.73 s

#### What behavior are you expecting?

no wranings

**Steps to reproduce:**
1. ionic start blank
2. ionic serve -c

**Which @ionic/app-scripts version are you using?**

3.13.2

**Comment by JosepAlacid** [comment]
On a mac os El Capitan the error is still going when ionic serve -l

**Comment by n0mer** [comment]
@mlynch why this issue is closed?

**Comment by kensodemann** [comment]
@n0mer - the `cordova.js` file is only included when you are running natively on a device, not when running in a browser. That is likely why this is closed.

https://stackoverflow.com/questions/43182619/cordova-js-not-available-while-running-in-chrome

**Comment by n0mer** [comment]
`ionic cordova run browser` will load those native plugins that support `browser` platform.

**Comment by n0mer** [comment]
anyway, in my case that error was caused by `--livereload` flag.

When i started w/out -lc (strange, but -c flag triggers -l as well), i got rid of this message, and debug via chrome://inspect#devices

**Comment by kensodemann** [comment]
OK, cool. Note that we generally do not suggest using the Cordova browser platform in general and rather suggest working around the fact that you do not have Cordova plugins in the browser by using native web APIs when Cordova is not present as outlined in the "Plugins" section of this document: https://ionicframework.com/docs/developer-resources/desktop-support/

But if using that platform works for you for testing, have at it.

**Comment by Bala22333** [comment]
How to fix cordova not available problem in ionic.Suggest me a solution for these...

**Comment by pakogn** [comment]
HI

I just faced this problem when using SQLite but I think is a general error dealing with cordova plugins. I found this and it worked like a charm.

I'm testing on an android device.

https://stackoverflow.com/questions/40815183/ionic-2-cordova-is-not-available-make-sure-to-include-cordova-js-or-run-in-a-d

@Bala22333

**Comment by elhamzaouiaymen** [comment]
@n0mer you saved my life ;) thanks.

**Comment by AdilShoukatConstant** [comment]
run after attaching device

`ionic cordova run android `

**Comment by huxforte** [comment]
> `ionic cordova run browser` will load those native plugins that support `browser` platform.

Cool

**Comment by michielwittkampf** [comment]
I removed the SplashScreen and StatusBar code from app.component.ts and app.component.ts (and in the related tests.)
That worked to remove the warnings.

I am on ionic 5.4.1.

**Comment by alimardani** [comment]
I am on ionic,
it might not be the best approach, But I just added a return to the beginning of the cordovaWarn function in common.js. will comment it whenever ready to publish to device.
![image](https://user-images.githubusercontent.com/3287533/68060667-94168380-fcbe-11e9-9ca8-abf513c1569f.png)
