### ISSUE TITLE
Follow up of IonicModule.forRoot() is missing deep-link-config that is refered to via a variable

### ISSUE THREAD

**Issue by fs5** [ionic-team/ionic-app-scripts#1295]
This ist a follow up of https://github.com/ionic-team/ionic-app-scripts/issues/1264 as I cannot reopen the original issue:

...

Thank you for the fix. It works for the case as described above. But it still fails when the deep-link-config is imported from another typescript file:

```javascript
import { DEEP_LINK_CONFIG } from "./app.routes";

const IONIC_CONFIG: any = { locationStrategy: 'hash' };

@NgModule({
  imports: [
    ...,
    IonicModule.forRoot(AppComponent, IONIC_CONFIG, DEEP_LINK_CONFIG)
  ],
  declarations: ...
})
export class AppModule { }
```

**Comment by fs5** [comment]
The previous fix was with commit 2e40340d348a8aadba38da371ad580e5070e7c3b

This seems to do the trick. Patching locally for the time being:

```javascript
if (deepLinkConfigArg.kind === SyntaxKind.Identifier) {
    return true;
}
```

**Comment by danbucholtz** [comment]
Wanna do a PR?

Thanks,
Dan

**Comment by fs5** [comment]
Sorry, it seems to be an issue with my installation. Npm kept installing version 3.0.0 although requesting 3.0.1 in package.json. Only after after setting it to ^3.0.1, the latest version was installed. Now, npm installs the correct version, even after reverting it back to 3.0.1. Looks like an issue with the node package manager to me.
