### ISSUE TITLE
when i ionic start new --type=ionic-angular,v4.5.3 node-sass is 404

### ISSUE THREAD

**Issue by shad0whz** [ionic-team/ionic-app-scripts#1303]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1. ionic start new --type=ionic-angular
2. v4.5.3 node-sass is 404

```
https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-59_binding.node

http error 404 not found
```

**Which @ionic/app-scripts version are you using?**
cli packages：
@ionic/cli-utils : 1.16.0
ionic( ionic CLI): 3.16.0

System:
node: v9.0.0
npm: 5.5.1
os: linux 4.13(ubuntu 17.10)

misc:
backend: pro

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danielsogl** [comment]
The required node-sass version is not ready for Nodejs 9. Please use the latest LTS release 8.9

**Comment by shad0whz** [comment]
thank you for your reply.
