### ISSUE TITLE
Lettable Rxjs operators and path-mapping

### ISSUE THREAD

**Issue by gregd** [ionic-team/ionic-app-scripts#1306]
After upgrade to Ionic 3.9.2 / app-scripts 3.1.0 / Angular 5, I updated my app to use lettable Rxjs operators. Everything works however in prod build the vendor.js file size increased. I guess that app-scripts build does not setup the path-mapping as described here https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#build-and-treeshaking

**Comment by peterpeterparker** [comment]
Kind of same here, analyzing source-map I see all `operators` included in `vendor.js`

I have migrated all `operator` to `operators`.

I still have some references to observable, like forkJoin, don't know if it's the same for you @gregd ? Could that be a reason too?

    import {Observable} from 'rxjs/Observable';
    import 'rxjs/add/observable/forkJoin';

<img width="1171" alt="capture d ecran 2017-11-09 a 12 40 56" src="https://user-images.githubusercontent.com/16886711/32603869-a15c13d6-c54b-11e7-98f1-204613175b24.png">

**Comment by mhartington** [comment]
Closing and moving to #1307

**Comment by peterpeterparker** [comment]
@gregd check the solution provided into  #1307 maybe you were doing the same mistake as I did?

**Comment by gregd** [comment]
@peterpeterparker At [Angular blog](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced) they recommend to use `import { map, filter } from 'rxjs/operators';` The other version `import { map } from 'rxjs/operators/map';` is proposed as a work around. So I still think that the `path-mapping` should be added to Ionic build process.

Anyway after moving to `import { map } from 'rxjs/operators/map';` style of imports, the vendor.js size was reduced. Now it is slightly smaller than the vendor.js build with Ionic 3.8 / Angular 4.4.4 version.

I guess that Ionic 4 will use different build system (maybe something based on angular-cli) and therefore Ionic guys don't want to spend time on polishing Ionic 3 build process.

**Comment by peterpeterparker** [comment]
@gregd congrats, cool to hear you find a solution and that your build went smaller!!!

may I ask, do you use other any other `add` Observables in your app?

like

    import 'rxjs/add/observable/forkJoin';
    import 'rxjs/add/observable/empty';
    etc.

I do and I kind of have the feeling that doing so, it cancel the advantages of selecting only selected `operators`. If I add such a piece of code, it looks like that many `operators` are loaded again. Not sure if it's design or I do something wrong...

**Comment by gregd** [comment]
@peterpeterparker I moved my code to `pipe(...)` and import operators like this
```
import {filter} from 'rxjs/operators/filter';
import {switchMap} from 'rxjs/operators/switchMap';
```
The changes are pretty automatic.

**Comment by peterpeterparker** [comment]
@gregd thx for the feedback, me too. I guess then that the use of `static` methods will result of importing `operators` in the bundle which are not directly referenced

found this https://github.com/ReactiveX/rxjs/issues/3059

**Comment by mhartington** [comment]
Just to add to this...

I think for now, using the deep imports is a better option. No build process changes are needed, and you still get the benefits of a smaller build.

**Comment by peterpeterparker** [comment]
@mhartington well I won't say `benefits of a smaller build` ... in my case, I use Rxjs static methods `forkJoin`, `fromPromise` and `empty` and  it looks like I sparred only 1kb ... but still better than bigger ;)
