### ISSUE TITLE
Replacement for node-sass?

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-app-scripts#1314]
Each time a new node version is released something like this happens for Windows users:

https://forum.ionicframework.com/t/newbie-ionic-start-already-failing-with-404-node-sass-not-found/112257

    [ERROR] An error occurred while running npm i (exit code 1):

        > node-sass@4.5.3 install D:\Repositories\Commercial\ridr.taxi\TestApp\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

        HTTP error 404 Not Found

This is for `Node : v9.2.0, npm: 5.5.1` this time.

Is there maybe an alternative to node-sass that doesn't break on Windows with each node update?

**Comment by mhartington** [comment]
I dont think we need to move off of node-sass, but keep pushing people to use the LTS version of node. This makes more sense to me.
