### ISSUE TITLE
[SOLVED]Error  Can't resolve './app.module.ngfactory' product error TS18003 in ngc

### ISSUE THREAD

**Issue by dbarrecoquel** [ionic-team/ionic-app-scripts#1325]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

Running the cli : ionic cordova run android --prod

#### What behavior are you expecting?

Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'C:\my_project_path\src\app'
resolve './app.module.ngfactory' in 'C:\my_project_path\src\app'
  using description file: C:\my_project_path\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\my_project_path\package.json (relative path: ./src/app)
    using description file: C:\my_project_path\package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\my_project_path\src\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\my_project_path\src\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\my_project_path\src\app\app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\my_project_path\src\app\app.module.ngfactory.json doesn't exist
      as directory
        C:\my_project_path\src\app\app.module.ngfactory doesn't exist
[C:\my_project_path\src\app\app.module.ngfactory]
[C:\my_project_path\src\app\app.module.ngfactory.ts]
[C:\my_project_path\src\app\app.module.ngfactory.js]
[C:\my_project_path\src\app\app.module.ngfactory.json]
[C:\my_project_path\src\app\app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at new BuildError (C:\my_project_path\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\my_project_path\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (C:\my_project_path\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\my_project_path\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\my_project_path\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\my_project_path\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\my_project_path\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\my_project_path\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\my_project_path\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (C:\my_project_path\node_modules\webpack\lib\Compiler.js:365:9)

**Steps to reproduce:**
1. run the cli command above
2. got this error
3. ngc give me :  error :TS18003

**Which @ionic/app-scripts version are you using?**

      @ionic/app-scripts : 3.1.2,
      typescript : 2.4.2

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

       error :TS18003: No inputs were found in config file 'tsconfig.json'. 
      Specified 'include' paths were '["**/*"]' and 'exclude' paths were   
      '["node_modules","bower_components","jspm_packages"]'.

ionic info : 
cli packages: (C:\Users\me\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.1
    npm  : 5.5.1
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : "C:\sdk_path"

Dependencies : 
  

       @angular/common: 5.0.2,
       @angular/compiler: 5.0.2,
       @angular/compiler-cli: 5.0.2,
       @angular/core: 5.0.2,
       @angular/forms: 5.0.2,
       @angular/http: 5.0.2,
       @angular/platform-browser: 5.0.2,
    @angular/platform-browser-dynamic: 5.0.2,
    @ionic-native/core: 4.4.0,
    @ionic-native/native-storage: ^4.4.2,
    @ionic-native/splash-screen: 4.4.0,
    @ionic-native/sqlite: ^4.4.2,
    @ionic-native/sqlite-porter: ^4.4.2,
    @ionic-native/status-bar: 4.4.0,
    @ionic/storage: 2.1.3,
    cordova-android: 6.3.0,
    cordova-plugin-device: ^1.1.4,
    cordova-plugin-ionic-webview: ^1.1.16,
    cordova-plugin-nativestorage: ^2.2.2,
    cordova-plugin-splashscreen: ^4.0.3,
    cordova-plugin-whitelist: ^1.3.1,
    cordova-sqlite-storage: ^2.1.2,
    ionic-angular: 3.9.2,
    ionic-plugin-keyboard: ^2.2.1,
    ionicons: 3.0.0,
    rxjs: 5.5.2,
    uk.co.workingedge.cordova.plugin.sqliteporter: ^1.0.2,
    zone.js: 0.8.18

**Comment by dbarrecoquel** [comment]
problem solved, it was a missing import component in a module... but the output error is not clear.

I found the error with this step  : 
- back to ionic-angular 3.8.0 and @angular/common,compiler..:4.4.4. 
- Tried a build : failed with a comprehensible output error
 - Correct it and update to 3.9.2 and that passed

**Comment by MarcioQuimbundo** [comment]
In my case, I updated @ionic/app-scripts to version 3.1.2 and works perfectly.
