### ISSUE TITLE
Files and line numbers missing from AoT errors

### ISSUE THREAD

**Issue by zbarbuto** [ionic-team/ionic-app-scripts#1330]
#### Short description of the problem:

dece39123ee1b794fd88abe6e74aa2dc658d4335 introduced a fix for AoT Angular error reporting which is great - few bugs found that I didn't know existed. Problem is that they don't report the line numbers or files of the errors which makes them impossible to track down:

```
11:30:17]  ngc started ...
[11:30:27]  typescript error
            Expected 0 arguments, but got 1.

[11:30:27]  typescript error
            Expected 1 arguments, but got 0.

[11:30:27]  typescript error
            Expected 1 arguments, but got 0.

[11:30:27]  ionic-app-script task: "build"
[11:30:27]  Error: The Angular AoT build failed. See the issues above
```

if I run `./node_modules/.bin/ngc` myself manually it will show the files and numbers which allows them to be fixed.

#### What behavior are you expecting?

AoT builds should show files and line nubmers of errors

**Which @ionic/app-scripts version are you using?**

3.1.3

**Comment by danbucholtz** [comment]
Fixed in `3.1.4`.

Thanks,
Dan
