### ISSUE TITLE
ionic cordova run android --prod not working 

### ISSUE THREAD

**Issue by SOUFIANEINPT** [ionic-team/ionic-app-scripts#1341]
#### What behavior are you expecting?
try run app in device by using --prod command 

**Steps to reproduce:**

C:\Users\INPT1\Desktop\ionic3\myApp>ionic cordova run android --prod
Running app-scripts build: --prod --platform android --target cordova
[10:16:02]  build prod started ...
[10:16:02]  clean started ...
[10:16:02]  clean finished in 6 ms
[10:16:02]  copy started ...
[10:16:03]  deeplinks started ...
[10:16:03]  deeplinks finished in 215 ms
[10:16:03]  ngc started ...
[10:16:18]  typescript error
            Type Tabs in C:/Users/INPT1/Desktop/ionic3/myApp/src/pages/tabs/tabs
.ts is part of the declarations of 2
            modules: AppModule in C:/Users/INPT1/Desktop/ionic3/myApp/src/app/ap
p.module.ts and TabsModule in
            C:/Users/INPT1/Desktop/ionic3/myApp/src/pages/tabs/tabs.module.ts! P
lease consider moving Tabs in
            C:/Users/INPT1/Desktop/ionic3/myApp/src/pages/tabs/tabs.ts to a high
er module that imports AppModule in
            C:/Users/INPT1/Desktop/ionic3/myApp/src/app/app.module.ts and TabsMo
dule in
            C:/Users/INPT1/Desktop/ionic3/myApp/src/pages/tabs/tabs.module.ts. Y
ou can also create a new NgModule that
            exports and includes Tabs in C:/Users/INPT1/Desktop/ionic3/myApp/src
/pages/tabs/tabs.ts then import that
            NgModule in AppModule in C:/Users/INPT1/Desktop/ionic3/myApp/src/app
/app.module.ts and TabsModule in
            C:/Users/INPT1/Desktop/ionic3/myApp/src/pages/tabs/tabs.module.ts.

Error: The Angular AoT build failed. See the issues above
    at C:\Users\INPT1\Desktop\ionic3\myApp\node_modules\@ionic\app-scripts\dist\
aot\aot-compiler.js:237:55
    at step (C:\Users\INPT1\Desktop\ionic3\myApp\node_modules\@ionic\app-scripts
\dist\aot\aot-compiler.js:32:23)
    at Object.next (C:\Users\INPT1\Desktop\ionic3\myApp\node_modules\@ionic\app-
scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (C:\Users\INPT1\Desktop\ionic3\myApp\node_modules\@ionic\app-sc
ripts\dist\aot\aot-compiler.js:4:58)
[10:16:18]  copy finished in 16.27 s
```
**Which @ionic/app-scripts version are you using?**


C:\Users\INPT1\Desktop\ionic3\myApp>ionic info

cli packages: (C:\Users\INPT1\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.10.0
    npm  : 5.5.1
    OS   : Windows 8.1

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro


C:\Users\INPT1\Desktop\ionic3\myApp>
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jcuervo** [comment]
`ionic cordova build android --prod --release` also FAILS with the same error that you posted.
Been looking for solutions for hours but no luck so far.

**Comment by SOUFIANEINPT** [comment]
can you put your issue here i fix my issue.

**Comment by mhartington** [comment]
Hi there! This is not an app-scripts error, but an error in your code setup. You're modules are not configured correctly. Please see this blog post and example apps for proper setup.

http://blog.ionicframework.com/ionic-and-lazy-loading-pt-2/

Thanks.

**Comment by jcuervo** [comment]
Haven't checked back and reworked for the Lazy Loading solution.
But what I did is remove all the `.module.ts` files, and the reference to `IonicPage` on the `.ts` files (with the `@IonicPage`). After doing this on all the new pages that I created, all went well.

Here are my dependencies:
```
  "dependencies": {
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/compiler-cli": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/device": "^4.4.2",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "^2.1.3",
    "chart.js": "^2.7.1",
    "cordova-android": "6.3.0",
    "cordova-ios": "4.5.4",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-whitelist": "^1.3.1",
    "cordova-sqlite-storage": "^2.1.2",
    "enhanced-resolve": "^3.3.0",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "nightly",
    "typescript": "2.4.2"
  },
```
