### ISSUE TITLE
Ionic 3 and white blank screen with android 4

### ISSUE THREAD

**Issue by fisher762** [ionic-team/ionic-app-scripts#1343]
Ionic 3 and white blank screen with android 4
Hello every one ,
I search everywhere to solve my problem
I finish my app and its works fine on browser but when I build apk or run it on emulator I got white blank page , I try default emulator , genymotion ,bluestak and memu emulators but all the same result .
Finally I install XWALK plugin to my app and now its works fine on my phone but it generate tow apk  android-armv7-debug.apk and android-x86-.apk now which apk I should publish to google play market to works fine on all devices
And is there any solution to app works without XWALK plugin ?

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with app-scripts it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead. Thanks!
