### ISSUE TITLE
[ionic serve]  Error ECONNRESET - Reload and websocket error breaks server  

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-app-scripts#1345]
#### Short description of the problem:

With the last update of Google Chrome, when I refresh a page, the local server (ionic server) breaks.

According @DeMoorJasper in the `parcel` project, the problem comes when disconnecting the client websocket from the server, which resulted in ECONNRESET, which was ignored in WS 3.3.2 but now triggers an unmatched error

According @imediasolutions downgrading the `ws` dependency of `ionic-app-scripts` solve the issue (see ionic forum)

#### What behavior are you expecting?

It should be possible to refresh or reload an app or page etc.

**Steps to reproduce:**
1. ionic serve
2. access http://localhost:8100 in Google Chrome (or Opera)
3. click refresh (in the browser)
=> server stops/breaks

**Log**

> [17:47:51]  sass finished in 1.92 s 
> [17:47:51]  postprocess started ... 
> [17:47:51]  postprocess finished in 235 ms 
> [17:47:51]  lint started ... 
> [17:47:51]  build dev finished in 30.50 s 
> [17:47:51]  watch ready in 30.75 s 
> [17:47:51]  dev server running: http://localhost:8100/ 
>
> [OK] Development server running!
>
>      Local: http://localhost:8100
>      External: http://192.168.43.103:8100, http://169.254.143.79:8100
>      DevApp: myapp@8100 on MyMacbook
> 
> [17:48:01]  lint finished in 9.88 s 
> events.js:136
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at _errnoException (util.js:999:13)
>     at TCP.onread (net.js:629:25)

**Other information:** 

Ionic forum: https://forum.ionicframework.com/t/ionic-serve-crash-on-save/115615
Parcel: https://github.com/parcel-bundler/parcel/issues/315

** Duplicate **

https://github.com/ionic-team/ionic-cli/issues/2921
https://github.com/ionic-team/ionic-app-scripts/issues/1344

**Comment by FazioNico** [comment]
Hi! got the same issue from yesterday. 
Can't work with my favorite browser Chrome.
There have any solution to fix it?? 
This solution NOT working for me: https://forum.ionicframework.com/t/ionic-serve-crash-on-save/115615/27

**Comment by yankedev** [comment]
I can confirm the issue is fixxed with ws@3.3.2

**Comment by villarres** [comment]
this solution works for myApp tabs but does not work with myApp blank and myApp sidemenu.
You can try them to see because npm install ws@3.3.2 resoud only for myApp tabs

**Comment by mhartington** [comment]
Hey there! Can you please install the nightly version of app-scripts to verify that all is fixed.

```
npm install @ionic/app-scripts@nightly --save-dev
```

This just pins the version to 3.3.2 for now until we properly update ws.

**Comment by mhartington** [comment]
3.1.6 is out now, which has the fix. Please upgrade your app-scripts version

**Comment by bernardlau92** [comment]
3.1.6 solves the issue. Thank you.

**Comment by peterpeterparker** [comment]
@mhartington thx, the fix works perfectly

**Comment by EugeneSnihovsky** [comment]
@mhartington It may be useful to update [ionic change log](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#upgrade-instructions-2) (version of ionic-app-script is hardcoded on **3.1.0** there)

**Comment by newsof1111** [comment]
have you try adding --local to your cmd?

**Comment by simonbrazell** [comment]
I'm still experiencing this issue on my Windows 7 machine:

```
[Wed Mar  7 12:45:01 2018] λ ionic info

cli packages: (C:\Users\sbrazell\AppData\Roaming\nvm\v8.9.4\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by cccaballero** [comment]
Hi guys, I still have the issue with Chrome

```
Your system information:

Cordova CLI: 6.0.0 
Ionic Framework Version: 3.9.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 3.1.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.2.1
Xcode version: Not installed
```

**Comment by LucaColombi** [comment]
me too, ionic serve on chrome crash at first reload, ionic serve -w firefox works without problems, error with chrome:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)

**Comment by maciejkoch** [comment]
+1

**Comment by sirius2013** [comment]
I got same issue.

**Comment by smallg** [comment]
thanks FazioNico, it fixed.
