### ISSUE TITLE
Node 9 Windows support

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic-app-scripts#1348]
#### Short description of the problem:
Actually ionic-app-scripts is not Node 9.x compatible on Windows because of the outdated node-sass dependency.

**Comment by pengkobe** [comment]
oh~ many days passed. your fix still not merged. that is frustrating..

**Comment by danielsogl** [comment]
@danbucholtz Can you take a look?

**Comment by raghulrajnkl** [comment]
i need right solutions to use node 9 with ionic 3.0
