### ISSUE TITLE
'ionic serve' sometimes serves old code

### ISSUE THREAD

**Issue by swvcc** [ionic-team/ionic-app-scripts#1442]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic serve sometimes serves old versions of my code

#### What behavior are you expecting?
not to do that.

**Steps to reproduce:**
1. run 'ionic serve'
2.test app for up to an hour.  at some point it will revert back to previous version.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
3.1.8

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by SonGokuSSGSS5** [comment]
+1 i put up the #1434  issue about a month ago,but my issue is always , still no response from the devs for almost a month

**Comment by mhartington** [comment]
This is a difficult issue to track down. In our tests, we have not been able to replicate this. So not sure how much more we can track down. If you dont mind, can you create a minimal test case app, and push it to github? This will help us best debug the issues

**Comment by mhartington** [comment]
merging with #1434
