### ISSUE TITLE
Enable CSS injection instead of full browser reload when changing global SCSS file

### ISSUE THREAD

**Issue by MilosR** [ionic-team/ionic-app-scripts#1443]
#### Short description of the problem:

Is there any way to configure CSS injection in browser when changing global SCSS files (eg. app.scss, not part of any component) and avoid full rebuild and browser refresh? It is very slow and time consuming in cases when you need custom styling.

#### What behavior are you expecting?

Live CSS inject / replacement, only CSS rebuild.

**Steps to reproduce:**
1. run "ionic serve"
2. change content of 'app.scss' file
3. you will see full rebuild, "rebuilding..." window in browser and browser refresh

**Which @ionic/app-scripts version are you using?**
```

cli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v9.5.0
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

Similar issues:

https://github.com/ionic-team/ionic-app-scripts/issues/387
https://github.com/angular/angular-cli/issues/3869

**Comment by mtuzinskiy** [comment]
I'm sorry to bother you, but why did you close it? @MilosR
