### ISSUE TITLE
prod environment variables are not passed in with --prod flag

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic-app-scripts#1485]
#### Short description of the problem:

`$ ionic cordova build ios` passes in the variables defined within .env.dev
`$ ionic cordova build ios --prod` does not pass in the variables defined within .env.prod.  Instead they are undefined.

#### What behavior are you expecting?

`$ ionic cordova build ios --prod` should pass in the production variables defined within .env.prod

**Steps to reproduce:**
1. Create an Ionic project
2. npm install @ionic/app-scripts@latest --save-dev
3. Create .env.dev, .env.prod and declarations.d.ts (as documented in the README)
4. Create a variable in .env.dev and .env.prod
4. Try building for with the --prod flag

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 14 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255

```

**Comment by smartameer** [comment]
In my case everything worked after using this command
`ionic cordova build ios -- --prod`

I am not sure why ionic lci works in this way but it expects most arguments with a blank `--`.

**Comment by TxusBlack** [comment]
> In my case everything worked after using this command
> `ionic cordova emulate ios -- --prod`
> `ionic cordova build ios -- --prod`
> 
> as internally it direct the command to `ionic-app-scripts` and that takes the argument `--prod`
> 
> I am not sure why `ionic-cli` works in this way but it expects most arguments with a blank `--`.

Not working for me.
