### ISSUE TITLE
 TypeError: Cannot read property 'getStart' of undefined

### ISSUE THREAD

**Issue by alphagamer7** [ionic-team/ionic-app-scripts#1512]
#### Short description of the problem:
<img width="1262" alt="screen shot 2019-02-02 at 1 27 56 am" src="https://user-images.githubusercontent.com/17358908/52146590-30f1b500-268a-11e9-9a0c-d7c63c2e234f.png">
When ionic build is run I get this error, probably since the `getStart` methods source is missing. Have installed the relevant typescript packages.
Have already tried removing node_modules and reinstalling, but ended up with same issue.

``` ionic-app-script task: "build"
TypeError: Cannot read property 'getStart' of undefined
TypeError: Cannot read property 'getStart' of undefined
```
#### What behavior are you expecting?
I want to successfully build the ionic project using ionic-app-script.

**Which @ionic/app-scripts version are you using?**
3.2.1

`package.json` file is as follows
```
{
  "name": "health-care",
  "version": "0.0.1",
  "author": "Athif",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "lint": "ionic-app-scripts lint",
    "test": "ng test",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@comparenetworks/imsmart-web": "5.0.20",
    "@ionic/angular": "^4.0.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^7.2.0",
    "@ngrx/router-store": "^7.2.0",
    "@ngrx/store": "^7.2.0",
    "@ngrx/store-devtools": "^7.2.0",
    "codelyzer": "~4.5.0",
    "core-js": "^2.5.4",
    "ionic-configuration-service": "^6.0.0",
    "lodash": "^4.17.11",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "tslint": "~5.12.1",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular/cli": "^7.3.0",
    "@ionic/app-scripts": "^3.2.1",
    "@types/lodash": "^4.14.117",
    "typescript": "3.2.1"
  },
  "description": "HealthCare"
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Possibly related - 
 [github.com/brackets-userland/brackets-typescript/issues/6](url)
[github.com/palantir/tslint-react/issues/87](url)
[https://stackoverflow.com/questions/54363489/having-an-error-at-build-time-showing-cannot-read-property-getstart-of-undefi](url)

**Comment by liamdebeasi** [comment]
Hi there, thanks for filing an issue with us.
Would you be able to provide the output from running `ionic info`?

Thanks for using Ionic!

**Comment by alphagamer7** [comment]
@liamdebeasi  `ionic info` is as follows: 
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.0
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61

**Comment by liamdebeasi** [comment]
Hi @alphagamer7,

Ionic 4 doesn't use ionic-app-scripts, so you can safely uninstall that. Additionally, I'd recommend updating the `scripts` section of your `package.json` with the ones found in the conference app: https://github.com/ionic-team/ionic-conference-app/blob/master/package.json.

I'm going to close this, but if you have more questions about migrating to Ionic 4, please consult the [Migration Guide](https://ionicframework.com/docs/building/migration) or create a post on the [forums](http://forum.ionicframework.com).

Thanks for using Ionic!
