### ISSUE TITLE
Using [chunkhash] in js filename does not work in --prod mode 

### ISSUE THREAD

**Issue by superkew** [ionic-team/ionic-app-scripts#797]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When using the built in webpack chunkhash feature to name a file, prod builds fail.

#### What behavior are you expecting?
Build to succeed with output file name using the injected chunkhash instead of the template snippet.

**Steps to reproduce:**
1. Start new ionic app from blank template with app-scripts v1.1.4
2. ionic build ios --prod --outputJsFileName main.[chunkhash:6].js
![screen shot 2017-03-07 at 08 33 35](https://cloud.githubusercontent.com/assets/8252497/23666775/cdcac24e-0310-11e7-8cfb-b92995795cb9.png)

```
[08:33:05]  transpile bundle started ... 
[08:33:05]  build prod failed: ENOENT: no such file or directory, open 
            '/Users/.../www/build/main.[chunkhash:6].js' 
[08:33:05]  ionic-app-script task: "build" 
[08:33:05]  Error: ENOENT: no such file or directory, open 
            '/Users/.../www/build/main.[chunkhash:6].js' 
at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at transpileBundleImpl (/Users/.../node_modules/@ionic/app-scripts/dist/transpile.js:253:34)
    at /Users/.../node_modules/@ionic/app-scripts/dist/transpile.js:245:16


```

**Which @ionic/app-scripts version are you using?**
1.1.4

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Related to https://github.com/driftyco/ionic-app-scripts/issues/741

The output file is generated correctly, but the prod build step is referencing the incorrect filename.

**Comment by superkew** [comment]
I'm guessing that the code on lines 313 and 314 in transpile.ts need to be updated to use the output.ChunkFilename (https://webpack.js.org/concepts/output/#output-chunkfilename). Not sure how, but I really hope it is possible.

```
const bundlePath = path.join(context.buildDir, process.env[Constants.ENV_OUTPUT_JS_FILE_NAME]);
const bundleContent = readFileSync(bundlePath).toString();
```

**Comment by twinj** [comment]
This is also an issue when using [name].bundle.js for the output file name. I have a couple entry files so need to specify the name so the outputs are correct.

**Comment by jgw96** [comment]
Hello all! At this time we cannot provide official support for custom webpack configs. I would recommend going to our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/) for help. Thanks for using Ionic!
