### ISSUE TITLE
ionic build android --prod successfully but its shows only white screen. but when i use ionic build android its work with 30sec booting time

### ISSUE THREAD

**Issue by abmnukmr** [ionic-team/ionic-app-scripts#800]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by themastersoda** [comment]
Can confirm. After building prod application is stuck with white screen on startup and inspecting shows error `Uncaught TypeError: Cannot read property '_' of undefined`. However, dev build works without any problems. The slow start of dev version is expected, so nothing unusual there. `serve` works fine as well.

**Comment by jafenchen** [comment]
i have the issue, how to fixed?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!
