### ISSUE TITLE
Watch fails on Ionic Serve

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-app-scripts#872]
_From @CarlosAyala on April 3, 2017 14:25_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Watch fails on Ionic Serve command.

"watch failed: A watch configured to watch the following paths failed to start. It likely that a file
 referenced does not exist: C:\wamp64\www\app\src\**\*.(ts|html|s(c|a)ss)"

**Expected behavior:**
No error

**Steps to reproduce:**

**Related code:**

```
{
  "name": "LifeLean_Mobile",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "angular-sortablejs": "^1.3.2",
    "dragula": "^3.7.2",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "ng2-animate": "^1.2.1",
    "ng2-dragula": "^1.2.2",
    "pouchdb": "^6.1.0",
    "pouchdb-adapter-cordova-sqlite": "^2.0.2",
    "pouchdb-find": "^0.10.4",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "@types/node": "^6.0.52",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-email-composer",
    "cordova-plugin-sqlite-2",
    "cordova-plugin-screen-orientation",
    "cordova-plugin-network-information",
    "cordova.plugins.diagnostic",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
        
  ],
  "cordovaPlatforms": [],
  "description": "mobile: An Ionic project"
}

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed
```

_Copied from original issue: driftyco/ionic#11029_

**Comment by danbucholtz** [comment]
How can I recreate this issue?

Thanks,
Dan

**Comment by leandroz** [comment]
Same here, I started a project with Ionic 2, then update it to Ionic 3, copying the package.json dependencies, npm install.
Later because I am using CLI v3 update it to use the beta versions and when you do serve is not watching the files.

Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.4 
    OS: macOS Sierra
    Node Version: v6.3.1
    Xcode version: Xcode 8.2 Build version 8C38

**Comment by leandroz** [comment]
@danbucholtz is there something I can do to debug this problem and help? its a pretty blocking issue

**Comment by leandroz** [comment]
Ok having () in your path breaks watch, rename a folder and its working now.

**Comment by fmss7** [comment]
@leandroz what do you mean by "rename a folder"? Could you explain it please? Thank you

**Comment by leandroz** [comment]
@fmss7 I had a folder name with parenthesis, that was breaking the watch of files for changes.

**Comment by danbucholtz** [comment]
It seems like this issue is resolved. Please let me know if it's not. I can't say I've heard of this one before 🐱 

Thanks,
Dan

**Comment by mindnervestech** [comment]
Please tell how you solved this issue
