### ISSUE TITLE
html-webpack-plugin temple no longer working in app-scripts 1.2.0+

### ISSUE THREAD

**Issue by superkew** [ionic-team/ionic-app-scripts#903]
#### Short description of the problem:
I use a custom index.html and the html-webpack-plugin to enable building my app for a webpage properly. Since the 1.2.0 update the template method doesn't run. I've kept the whole app at ionic version 3 and downgraded app-scripts to 1.1.4 and then the templating works just fine.

#### What behavior are you expecting?
I'm expecting code blocks like this to work correctly and inject script tags.

```
<!-- The bundle js is generated during the build process -->
  <% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
  <script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
  <% } %>
```

**Steps to reproduce:**
1. Install html-webpack-plugin plugin
2. Use custom webpack config like so
```
var baseConfig = require('../node_modules/@ionic/app-scripts/config/webpack.config.js');
var HtmlWebpackPlugin = require('html-webpack-plugin');


baseConfig.plugins.push(new HtmlWebpackPlugin({
  template: './src/index.html',
  inject: false,
  hash: false,
  filename: '../index.html'
}));

module.exports = baseConfig;
```
3. replace 
```
 <!-- The bundle js is generated during the build process -->
  <script src="build/main.js"></script>
```
with 
```
 <% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
  <script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
  <% } %>
```

**Which @ionic/app-scripts version are you using?**
1.1.4 working
1.2.0+ does not work

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, Here is a repo that reproduces the issue off a new ionic app.
https://github.com/superkew/ionic-2-sandbox

run ionic build when app-scripts is v1.2.0+ and see www/index.html
run ionic build when app-scripts is v1.1.4 and see www/index.html

**Comment by superkew** [comment]
Here is a repo that reproduces the issue off a new ionic app.
https://github.com/superkew/ionic-2-sandbox

run ionic build when app-scripts is v1.2.0+ and see www/index.html
run ionic build when app-scripts is v1.1.4 and see www/index.html

**Comment by superkew** [comment]
I found the commit that breaks the plugin.

https://github.com/driftyco/ionic-app-scripts/commit/09e11399e1beebbf8be810fadde0e8a5be49feaf

**Comment by superkew** [comment]
I hope there is another fix to this other than the proposed one in the simple PR I submitted. This plugin seems to be the go-to when implementing cache busting with webpack.

**Comment by jgw96** [comment]
Hello, at this time we cannot provide official support for custom webpack configs. I would recommend checking out our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/) for help. Thanks for using Ionic!
