### ISSUE TITLE
Installation problem with ubuntu 16.4

### ISSUE THREAD

**Issue by Mdhaker** [ionic-team/ionic-app-scripts#913]
I'm runing ubuntu 16.4, when I try to install the ionic-app-scripts via npm it gives this log : 

>  `├── UNMET PEER DEPENDENCY @angular/compiler@*
> ├── UNMET PEER DEPENDENCY @angular/compiler-cli@*
> ├── UNMET PEER DEPENDENCY @angular/tsc-wrapped@*
> ├─┬ @ionic/app-scripts@1.3.4 
> │ └── UNMET PEER DEPENDENCY typescript@>=1.7.3
> ├── UNMET PEER DEPENDENCY sw-toolbox@*
> ├── UNMET PEER DEPENDENCY typescript@*
> └── UNMET PEER DEPENDENCY zone.js@*
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN @angular/core@2.4.1 requires a peer of zone.js@^0.7.2 but none was installed.
> npm WARN @ionic/app-scripts@1.3.4 requires a peer of @angular/compiler@* but none was installed.
> npm WARN @ionic/app-scripts@1.3.4 requires a peer of @angular/compiler-cli@* but none was installed.
> npm WARN @ionic/app-scripts@1.3.4 requires a peer of @angular/tsc-wrapped@* but none was installed.
> npm WARN @ionic/app-scripts@1.3.4 requires a peer of sw-toolbox@* but none was installed.
> npm WARN @ionic/app-scripts@1.3.4 requires a peer of typescript@* but none was installed.
> npm WARN @ionic/app-scripts@1.3.4 requires a peer of zone.js@* but none was installed.
> npm WARN tslint@3.15.1 requires a peer of typescript@>=1.7.3 but none was installed.
> npm WARN promowinner@1.1.1 No repository field.
> npm WARN promowinner@1.1.1 No license field.`

and when try to excute npm run build it gives this error 

> npm run build
npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v4.2.0

npm ERR! missing script: build

**Comment by mburger81** [comment]
Did you run npm install?  Can you share your package.json?

**Comment by Mdhaker** [comment]
Yes I did run the npm install which gave me also the log I'v posted, the package.json still doesn't have ionic-app-scripts `{
  "name": "promowinner",
  "version": "1.1.1",
  "description": "promowinner: An Ionic project",
  "dependencies": {
    "@ionic/cloud": "^0.14.1",
    "@ionic/cloud-angular": "^0.8.0",
    "bluebird": "^3.4.7",
    "gulp": "^3.5.6",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^2.0.4"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp-util": "^2.2.14",
    "shelljs": "^0.3.0"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}
`

**Comment by jgw96** [comment]
Hello @Mdhaker , if you update to the [latest node LTS release](https://nodejs.org/en/download/) do you still get the same error?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
