### ISSUE TITLE
Error: Cannot find module "dns"

### ISSUE THREAD

**Issue by nfantone** [ionic-team/ionic-app-scripts#956]
#### Short description of the problem:

~~This happened after issuing the first `ionic serve` with `ionic CLI 3.0.0-rc.1`.~~ _Not related to upgrade: read comment below_.
After `ionic serve` (which runs without errors), a browser tab is opened showing the following error:

```sh
Runtime Error
Cannot find module "dns"

Stack
Error: Cannot find module "dns"
    at d (http://localhost:8100/build/polyfills.js:3:3991)
    at webpackMissingModule (http://localhost:8100/build/main.js:160086:75)
```

#### What behavior are you expecting?
Seeing my application running in the browser.

**Which @ionic/app-scripts version are you using?**

```sh
Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.6
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 7.9.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3087.0 Safari/537.36
```

**Other information:** 
- Commenting out the line in `main.js:160086` revealed by the stack trace on the error seems to resolve the issue:

```js
// var Dns = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"dns\""); e.code = 'MODULE_NOT_FOUND';; throw e; }()));
```

- Adding the following to `@ionic/app-scripts/config/webpack.config.js` also makes everything work:

```diff
  node: {
+   dns: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```

**Comment by nfantone** [comment]
Found out that running `ionic cordova build android --debug` outputs a much clearer error for the same issue:

```sh
{ Error: ./~/isemail/lib/isemail.js
Module not found: Error: Can't resolve 'dns' in '/home/travis/build/crash7/gdr-m-commerce/node_modules/isemail/lib'
resolve 'dns' in '/home/travis/build/crash7/gdr-m-commerce/node_modules/isemail/lib'
  Parsed request is a module
  using description file: /home/travis/build/crash7/gdr-m-commerce/node_modules/isemail/package.json 
# ...
 @ ./~/isemail/lib/isemail.js 44:10-24
 @ ./~/isemail/index.js
 @ ./~/joi/lib/string.js
 @ ./~/joi/lib/index.js
 @ ./~/jsonwebtoken/sign.js
 @ ./~/jsonwebtoken/index.js
 @ ./src/auth/token/token.service.ts
 @ ./src/auth/auth.module.ts
 @ ./src/pages/login/login.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
```

It now seems to me that the `dns` dependency comes from having installed `jsonwebtoken`. It which [uses `joi`](https://github.com/auth0/node-jsonwebtoken/blob/master/package.json#L22), which [depends on `isemail`](https://github.com/hapijs/joi/blob/master/package.json#L18), which [requires `dns`](https://github.com/hapijs/isemail/blob/master/lib/index.js#L5).

I believe the `'empty'` webpack mock for [node's native dns](https://nodejs.org/dist/latest-v6.x/docs/api/dns.html) should be appended to the configuration?

**Comment by danbucholtz** [comment]
I'm not sure, I copy and pasted that part of the webpack config from `create-react-app`. Can you try messing with that value and see what works?

Thanks,
Dan

**Comment by nfantone** [comment]
@danbucholtz You mean [this bit over here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js)? You are right in that it doesn't provide a mock for `dns`. And it suffers from the exact same issue.

Just follow these steps to see what I mean:

```sh
npm i -g create-react-app
create-react-app my-app
cd ./my-app
npm i --save jsonwebtoken
```

Open `src/App.js` and import `jsonwebtoken`:

```diff
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
+ import * as JWT from 'jsonwebtoken';

class App extends Component {
// ...
```

Run the application:

```sh
yarn start
```

You'll be greeted with the same error from [my previous comment](https://github.com/driftyco/ionic-app-scripts/issues/956#issuecomment-298806089):

```sh
Failed to compile.

Error in ./~/isemail/lib/isemail.js
Module not found: 'dns' in /Users/nfantone/my-app/node_modules/isemail/lib

 @ ./~/isemail/lib/isemail.js 45:10-24
```

**Comment by danbucholtz** [comment]
Not sure. Can you follow the instructions on the readme and provide your own Webpack config?

Thanks,
Dan

**Comment by nfantone** [comment]
@danbucholtz I'm sorry: what `README.md` would that be? This project's?

I did that, already. If you provide a custom `webpack.config.js` including [what I mentioned on the original comment](https://github.com/driftyco/ionic-app-scripts/issues/956#issue-225839488), it works as expected. So perhaps you can consider the issue part of "user land" and close it. I'm not sure about the benefits of always mocking `dns` vs. not doing it.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! As this is not really a common issue as there are a tiny amount of libs that need the `dns` module mocked I am going to consider this a `user land` issue and close this for now.
