### ISSUE TITLE
(v3)linting is not working..

### ISSUE THREAD

**Issue by sfabriece** [ionic-team/ionic-app-scripts#967]
What version of the CLI are you using? Output of ionic --version

3.0.0-rc.1

Short description of the problem:

if have the following script defined in 'package.json'

`"lint": "ionic-app-scripts lint"` 

When I run it, doesn't produce any errors even though vscode is showing the errors.

the output

```
> ionic-app-scripts lint

[10:54:42]  ionic-app-scripts 1.3.7
[10:54:42]  lint started ...
[10:54:46]  lint finished in 3.28 s
```

What behavior are you expecting?

linting to work

Post the output of ionic info below please

global packages:

    @ionic/cli-utils : 1.0.0-rc.1
    Ionic CLI        : 3.0.0-rc.1

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.1
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.8.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

part of my  package.json:
```
"scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/common": "4.1.1",
    "@angular/compiler": "4.1.1",
    "@angular/compiler-cli": "4.1.1",
    "@angular/core": "4.1.1",
    "@angular/forms": "4.1.1",
    "@angular/http": "4.1.1",
    "@angular/platform-browser": "4.1.1",
    "@angular/platform-browser-dynamic": "4.1.1",
    "@angular/platform-server": "4.1.1",
    "@ionic-native/core": "^3.6.1",
    "@ionic-native/app-version": "^3.6.1",
    "@ionic-native/in-app-browser": "^3.6.1",
    "@ionic-native/network": "^3.6.1",
    "@ionic-native/splash-screen": "^3.6.1",
    "@ionic-native/status-bar": "^3.6.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.1.1",
    "ionicons": "~3.0.0",
    "rxjs": "5.3.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.10"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.7",
    "@ionic/cli-build-ionic-angular": "0.0.4",
    "@ionic/cli-plugin-cordova": "^1.0.0-rc.1",
    "@ionic/cli-plugin-ionic-angular": "^1.0.0-rc.1",
    "tslint": "^5.1.0",
    "typescript": "~2.2.2"
  },
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. I am unfortunately not able to reproduce this issue. Are the errors showing in vscode linter errors or runtime errors ? For example, if you hover over the red squiggly does it say something like this ```[tslint] Unused variable: 'popover' (no-unused-variable ```

**Comment by StrongTS** [comment]
I have the same problem

**Comment by gritzley** [comment]
I am having this issue as well and I can't find any solution. How did you manage to solve this in the end?
